/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Build and environment metadata (public) */
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Build and environment metadata */
        MetaResponse: {
            /** @example OrenjiTrade API */
            name: string;
            /** @example 0.1.0 */
            version: string;
            /** @example local */
            environment: string;
            /** Format: date-time */
            serverTime: string;
        };
        /** @description RFC 9457 problem details with OrenjiTrade extensions */
        ProblemDetail: {
            /** Format: uri */
            type: string;
            title: string;
            /** Format: int32 */
            status: number;
            detail?: string;
            instance?: string;
            /**
             * @example VALIDATION_FAILED
             * @enum {string}
             */
            errorCode: "VALIDATION_FAILED" | "NOT_FOUND" | "FORBIDDEN" | "UNAUTHENTICATED" | "CONFLICT" | "RATE_LIMITED" | "PAYLOAD_TOO_LARGE" | "UNSUPPORTED_MEDIA_TYPE" | "INTERNAL_ERROR" | "SERVICE_UNAVAILABLE";
            message: string;
            requestId: string;
            /** Format: date-time */
            timestamp: string;
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
            /** @description Error (RFC 9457 problem details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
