/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AccountExport } from '../model/models';
import { CreateDeletionRequest } from '../model/models';
import { DeletionRequestResponse } from '../model/models';
import { ProblemDetail } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CancelAccountDeletionRequestParams {
    id: string;
}

export interface RequestAccountDeletionRequestParams {
    createDeletionRequest: CreateDeletionRequest;
}


export interface AccountServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Cancel a pending deletion during the grace period
     * Re-activates the account (and its map presence). 404 when the request is not the caller\&#39;s, 409 when it is no longer pending.
     * @endpoint delete /api/v1/me/deletion-requests/{id}
* @param requestParameters
     */
    cancelAccountDeletion(requestParameters: CancelAccountDeletionRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Download the caller\&#39;s data
     * JSON document with one section per module (account + consents, profile + tags + privacy settings, notification preferences, location, ...). Served as an attachment. Rate-limited (10 per hour); also available while a deletion is pending.
     * @endpoint get /api/v1/me/export
*/
    exportMyData(extraHttpRequestParams?: any): Observable<AccountExport>;

    /**
     * The caller\&#39;s deletion requests
     * Newest first; lets clients find the pending request to cancel it after a reload.
     * @endpoint get /api/v1/me/deletion-requests
*/
    listAccountDeletionRequests(extraHttpRequestParams?: any): Observable<Array<DeletionRequestResponse>>;

    /**
     * Request the deletion of the caller\&#39;s account
     * Needs an ID token whose &#x60;auth_time&#x60; is at most 5 minutes old (401 REAUTHENTICATION_REQUIRED otherwise). On success the account becomes DELETION_REQUESTED, every identity-provider session is revoked (signed out everywhere; signing in again only gives access to GET /me, GET /me/export and these deletion endpoints), the collector disappears from the map and the deletion runs after a 7-day grace period. 409 DELETION_BLOCKED (extension &#x60;blockers[]&#x60;) while obligations are open; 409 CONFLICT when a request is already pending.
     * @endpoint post /api/v1/me/deletion-requests
* @param requestParameters
     */
    requestAccountDeletion(requestParameters: RequestAccountDeletionRequestParams, extraHttpRequestParams?: any): Observable<DeletionRequestResponse>;

}
