/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AdminDashboard } from '../model/models';
import { ProblemDetail } from '../model/models';
import { SystemHealth } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminConsoleServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Dashboard counters (ADMIN)
     * Accounts, active collectors of the last 7 days, public items and binders, open and unassigned reports, open moderation flags, stale and hidden listings, owners with paused listings, open disputes and webhook failures (0 until Phase 9) and notifications whose push or email failed in the last 24 hours.
     * @endpoint get /api/v1/admin/dashboard
*/
    getAdminDashboard(extraHttpRequestParams?: any): Observable<AdminDashboard>;

    /**
     * System health (ADMIN)
     * Actuator health (overall and per component, statuses only), the event outbox backlog (incomplete publications and the oldest one), notifications waiting for dispatch and the last run of every job (job_run).
     * @endpoint get /api/v1/admin/system/health
*/
    getSystemHealth(extraHttpRequestParams?: any): Observable<SystemHealth>;

}
