/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PageResponseAuditLogEntry } from '../model/models';
import { ProblemDetail } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ListAuditLogsRequestParams {
    actorId?: string;
    targetType?: string;
    targetId?: string;
    action?: string;
    from?: string;
    to?: string;
    page?: number;
    size?: number;
}


export interface AdminAuditServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * List audit-log entries (ADMIN, SUPER_ADMIN)
     * Newest first. Every filter is optional; &#x60;from&#x60; is inclusive, &#x60;to&#x60; exclusive.
     * @endpoint get /api/v1/admin/audit-logs
* @param requestParameters
     */
    listAuditLogs(requestParameters: ListAuditLogsRequestParams, extraHttpRequestParams?: any): Observable<PageResponseAuditLogEntry>;

}
