/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { FeatureFlag } from '../model/models';
import { ProblemDetail } from '../model/models';
import { UpdateFeatureFlagRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface UpdateFeatureFlagRequestParams {
    key: string;
    updateFeatureFlagRequest: UpdateFeatureFlagRequest;
}


export interface AdminFeatureFlagsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * List feature flags (ADMIN, SUPER_ADMIN)
     * Every flag with its rollout, description and last editor, by key.
     * @endpoint get /api/v1/admin/feature-flags
*/
    listFeatureFlags(extraHttpRequestParams?: any): Observable<Array<FeatureFlag>>;

    /**
     * Change a feature flag (SUPER_ADMIN)
     * Flags are created by migrations; unknown keys are 404. Takes effect on every instance at once (cache evicted). Audited (&#x60;feature_flag.update&#x60;).
     * @endpoint put /api/v1/admin/feature-flags/{key}
* @param requestParameters
     */
    updateFeatureFlag(requestParameters: UpdateFeatureFlagRequestParams, extraHttpRequestParams?: any): Observable<FeatureFlag>;

}
