/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AdminPlan } from '../model/models';
import { AdminUsageLimit } from '../model/models';
import { Entitlement } from '../model/models';
import { GrantEntitlementRequest } from '../model/models';
import { ProblemDetail } from '../model/models';
import { UpdatePlanRequest } from '../model/models';
import { UpdateUsageLimitRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GrantEntitlementRequestParams {
    id: string;
    grantEntitlementRequest: GrantEntitlementRequest;
}

export interface ListUsageLimitsRequestParams {
    plan?: string;
}

export interface ListUserEntitlementsRequestParams {
    id: string;
}

export interface RevokeEntitlementRequestParams {
    id: string;
    entitlementId: string;
}

export interface UpdatePlanRequestParams {
    code: string;
    updatePlanRequest: UpdatePlanRequest;
}

export interface UpdateUsageLimitRequestParams {
    id: string;
    updateUsageLimitRequest: UpdateUsageLimitRequest;
}


export interface AdminPlansServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Grant an entitlement (ADMIN, SUPER_ADMIN)
     * Overrides a plan limit (&#x60;value&#x60; &#x3D; number or &#x60;unlimited&#x60;) or feature (&#x60;true&#x60; / &#x60;false&#x60;) for one account, optionally until &#x60;expiresAt&#x60;. Takes effect at once. Audited (&#x60;entitlement.grant&#x60;).
     * @endpoint post /api/v1/admin/users/{id}/entitlements
* @param requestParameters
     */
    grantEntitlement(requestParameters: GrantEntitlementRequestParams, extraHttpRequestParams?: any): Observable<Entitlement>;

    /**
     * List plans with features and limits (ADMIN, SUPER_ADMIN)
     * Active and inactive plans, by sort order.
     * @endpoint get /api/v1/admin/plans
*/
    listAdminPlans(extraHttpRequestParams?: any): Observable<Array<AdminPlan>>;

    /**
     * List usage limits (ADMIN, SUPER_ADMIN)
     * Every limit of every plan (optionally one plan), by plan then key.
     * @endpoint get /api/v1/admin/usage-limits
* @param requestParameters
     */
    listUsageLimits(requestParameters: ListUsageLimitsRequestParams, extraHttpRequestParams?: any): Observable<Array<AdminUsageLimit>>;

    /**
     * Entitlements of an account (ADMIN, SUPER_ADMIN)
     * Active, expired and revoked entitlements, newest first.
     * @endpoint get /api/v1/admin/users/{id}/entitlements
* @param requestParameters
     */
    listUserEntitlements(requestParameters: ListUserEntitlementsRequestParams, extraHttpRequestParams?: any): Observable<Array<Entitlement>>;

    /**
     * Revoke an entitlement (ADMIN, SUPER_ADMIN)
     * 404 when the entitlement does not belong to the account or is no longer active. Audited (&#x60;entitlement.revoke&#x60;).
     * @endpoint delete /api/v1/admin/users/{id}/entitlements/{entitlementId}
* @param requestParameters
     */
    revokeEntitlement(requestParameters: RevokeEntitlementRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Change a plan (SUPER_ADMIN)
     * Name, description, display price, active flag, order and feature switches (listed features are upserted). FREE cannot be disabled. Audited (&#x60;plan.update&#x60;).
     * @endpoint put /api/v1/admin/plans/{code}
* @param requestParameters
     */
    updatePlan(requestParameters: UpdatePlanRequestParams, extraHttpRequestParams?: any): Observable<AdminPlan>;

    /**
     * Change a usage limit (SUPER_ADMIN)
     * Live edit: every instance applies the new value at once (cache evicted); counters keep their usage. Audited (&#x60;usage_limit.update&#x60;).
     * @endpoint put /api/v1/admin/usage-limits/{id}
* @param requestParameters
     */
    updateUsageLimit(requestParameters: UpdateUsageLimitRequestParams, extraHttpRequestParams?: any): Observable<AdminUsageLimit>;

}
