/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AdminListing } from '../model/models';
import { HideListingRequest } from '../model/models';
import { PageResponseAdminListing } from '../model/models';
import { PageResponseStaleListing } from '../model/models';
import { ProblemDetail } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface HideListingRequestParams {
    itemId: string;
    hideListingRequest: HideListingRequest;
}

export interface ListAdminListingsRequestParams {
    query?: string;
    state?: 'ACTIVE' | 'AGING' | 'STALE' | 'HIDDEN';
    game?: string;
    ownerId?: string;
    page?: number;
    size?: number;
}

export interface ListStaleListingsRequestParams {
    state?: 'ACTIVE' | 'AGING' | 'STALE' | 'HIDDEN';
    page?: number;
    size?: number;
}

export interface RestoreListingRequestParams {
    itemId: string;
}


export interface AdminListingsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Hide a listing (ADMIN)
     * Makes the item PRIVATE (the owner can publish it again). Audited (&#x60;listing.hide&#x60; with the reason).
     * @endpoint post /api/v1/admin/listings/{itemId}/hide
* @param requestParameters
     */
    hideListing(requestParameters: HideListingRequestParams, extraHttpRequestParams?: any): Observable<AdminListing>;

    /**
     * List listings (ADMIN)
     * Items their owners made public or temporarily public (effectivePublic says whether they are public right now), newest change first. &#x60;query&#x60; matches card names, printing codes and sets; &#x60;state&#x60; is the freshness state.
     * @endpoint get /api/v1/admin/listings
* @param requestParameters
     */
    listAdminListings(requestParameters: ListAdminListingsRequestParams, extraHttpRequestParams?: any): Observable<PageResponseAdminListing>;

    /**
     * Stale and hidden listings for review (ADMIN)
     * STALE or HIDDEN listings (both when &#x60;state&#x60; is omitted), oldest confirmation first, with the warning time. Nothing is ever deleted by the freshness rules; POST /admin/listings/{itemId}/restore confirms a listing again.
     * @endpoint get /api/v1/admin/listings/stale
* @param requestParameters
     */
    listStaleListings(requestParameters: ListStaleListingsRequestParams, extraHttpRequestParams?: any): Observable<PageResponseStaleListing>;

    /**
     * Restore a stale or hidden listing (ADMIN)
     * Confirms the listing on the owner\&#39;s behalf (freshness ACTIVE again, RESTORED event). Audited (&#x60;listing.restore&#x60;).
     * @endpoint post /api/v1/admin/listings/{itemId}/restore
* @param requestParameters
     */
    restoreListing(requestParameters: RestoreListingRequestParams, extraHttpRequestParams?: any): Observable<AdminListing>;

}
