export * from './account.service';
import { AccountService } from './account.service';
export * from './account.serviceInterface';
export * from './adminAudit.service';
import { AdminAuditService } from './adminAudit.service';
export * from './adminAudit.serviceInterface';
export * from './adminUsers.service';
import { AdminUsersService } from './adminUsers.service';
export * from './adminUsers.serviceInterface';
export * from './collectors.service';
import { CollectorsService } from './collectors.service';
export * from './collectors.serviceInterface';
export * from './internal.service';
import { InternalService } from './internal.service';
export * from './internal.serviceInterface';
export * from './legal.service';
import { LegalService } from './legal.service';
export * from './legal.serviceInterface';
export * from './location.service';
import { LocationService } from './location.service';
export * from './location.serviceInterface';
export * from './me.service';
import { MeService } from './me.service';
export * from './me.serviceInterface';
export * from './meta.service';
import { MetaService } from './meta.service';
export * from './meta.serviceInterface';
export * from './profile.service';
import { ProfileService } from './profile.service';
export * from './profile.serviceInterface';
export * from './public.service';
import { PublicService } from './public.service';
export * from './public.serviceInterface';
export * from './settings.service';
import { SettingsService } from './settings.service';
export * from './settings.serviceInterface';
export const APIS = [AccountService, AdminAuditService, AdminUsersService, CollectorsService, InternalService, LegalService, LocationService, MeService, MetaService, ProfileService, PublicService, SettingsService];
