export * from './adminAudit.service';
import { AdminAuditService } from './adminAudit.service';
export * from './adminAudit.serviceInterface';
export * from './adminUsers.service';
import { AdminUsersService } from './adminUsers.service';
export * from './adminUsers.serviceInterface';
export * from './internal.service';
import { InternalService } from './internal.service';
export * from './internal.serviceInterface';
export * from './legal.service';
import { LegalService } from './legal.service';
export * from './legal.serviceInterface';
export * from './me.service';
import { MeService } from './me.service';
export * from './me.serviceInterface';
export * from './meta.service';
import { MetaService } from './meta.service';
export * from './meta.serviceInterface';
export const APIS = [AdminAuditService, AdminUsersService, InternalService, LegalService, MeService, MetaService];
