/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AccountDeletionJobResponse } from '../model/models';
import { PingJobResponse } from '../model/models';
import { ProblemDetail } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface InternalServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Connectivity check for schedulers (service auth)
     * Records a &#x60;ping&#x60; job run and answers &#x60;{ \&quot;ok\&quot;: true }&#x60;.
     * @endpoint post /internal/jobs/ping
*/
    pingInternalJobs(extraHttpRequestParams?: any): Observable<PingJobResponse>;

    /**
     * Process due account deletions (service auth)
     * Anonymises every account whose grace period is over, purges module data, deletes the identity-provider user and records a job run. Consents, audit entries and ledgers are kept.
     * @endpoint post /internal/jobs/account-deletion
*/
    runAccountDeletionJob(extraHttpRequestParams?: any): Observable<AccountDeletionJobResponse>;

}
