/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AccountDeletionJobResponse } from '../model/models';
import { DelistJobResponse } from '../model/models';
import { FreshnessJobResponse } from '../model/models';
import { PingJobResponse } from '../model/models';
import { ProblemDetail } from '../model/models';
import { UploadCleanupJobResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface InternalServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Connectivity check for schedulers (service auth)
     * Records a &#x60;ping&#x60; job run and answers &#x60;{ \&quot;ok\&quot;: true }&#x60;.
     * @endpoint post /internal/jobs/ping
*/
    pingInternalJobs(extraHttpRequestParams?: any): Observable<PingJobResponse>;

    /**
     * Process due account deletions (service auth)
     * Anonymises every account whose grace period is over, purges module data, deletes the identity-provider user and records a job run. Consents, audit entries and ledgers are kept.
     * @endpoint post /internal/jobs/account-deletion
*/
    runAccountDeletionJob(extraHttpRequestParams?: any): Observable<AccountDeletionJobResponse>;

    /**
     * Pause listings of unresponsive owners (service auth)
     * Daily. Pauses the public listings of owners whose unresponsiveness strikes reached the policy\&#39;s maxStrikes. Strike tracking arrives with Phases 5/7: until then the run is recorded and nobody is paused. Never deletes.
     * @endpoint post /internal/jobs/delist
*/
    runDelistJob(extraHttpRequestParams?: any): Observable<DelistJobResponse>;

    /**
     * Recompute listing freshness (service auth)
     * Hourly. Expired temporary publications become PRIVATE; freshness states of items and binders are re-derived from confirmedAt and the active delist policy; public listings entering the warning window are warned once; hidden listings stop being public (InventoryItemUnpublished). Never deletes. Records a job run.
     * @endpoint post /internal/jobs/freshness
*/
    runFreshnessJob(extraHttpRequestParams?: any): Observable<FreshnessJobResponse>;

    /**
     * Delete unattached image uploads (service auth)
     * Every 15 minutes. Deletes image uploads older than 1 h that no message consumed, with their stored objects. Records a job run.
     * @endpoint post /internal/jobs/upload-cleanup
*/
    runUploadCleanupJob(extraHttpRequestParams?: any): Observable<UploadCleanupJobResponse>;

}
