/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ConsentRequest } from '../model/models';
import { MeResponse } from '../model/models';
import { PingResponse } from '../model/models';
import { ProblemDetail } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AcceptConsentRequestParams {
    consentRequest: ConsentRequest;
}


export interface MeServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Accept a legal document version
     * Stores the version, timestamp, a salted hash of the client IP and the user agent. 409 when the version is not the current one.
     * @endpoint post /api/v1/me/consents
* @param requestParameters
     */
    acceptConsent(requestParameters: AcceptConsentRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Current account
     * Provisions the account on the first call. Exempt from the terms-acceptance check so clients can discover &#x60;requiredConsents&#x60;.
     * @endpoint get /api/v1/me
*/
    getMe(extraHttpRequestParams?: any): Observable<MeResponse>;

    /**
     * Authenticated connectivity check
     * Cheapest authenticated call: refreshes the caller\&#39;s last-active timestamp and is subject to the terms-acceptance check like every other route.
     * @endpoint get /api/v1/me/ping
*/
    pingMe(extraHttpRequestParams?: any): Observable<PingResponse>;

}
