/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { MetaResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MetaServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Build and environment metadata (public)
     * 
     * @endpoint get /api/v1/meta
*/
    getMeta(extraHttpRequestParams?: any): Observable<MetaResponse>;

}
