/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CursorPageNotificationResponse } from '../model/models';
import { NotificationResponse } from '../model/models';
import { ProblemDetail } from '../model/models';
import { PushTokenRequest } from '../model/models';
import { ReadAllNotificationsResponse } from '../model/models';
import { UnreadNotificationCount } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface DeletePushTokenRequestParams {
    token: string;
}

export interface ListNotificationsRequestParams {
    cursor?: string;
    limit?: number;
    unreadOnly?: boolean;
}

export interface MarkNotificationReadRequestParams {
    id: string;
}

export interface RegisterPushTokenRequestParams {
    pushTokenRequest: PushTokenRequest;
}


export interface NotificationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Remove a device push token (sign-out)
     * Idempotent; tokens of other accounts are left untouched.
     * @endpoint delete /api/v1/me/push-tokens/{token}
* @param requestParameters
     */
    deletePushToken(requestParameters: DeletePushTokenRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Number of unread notifications (badge)
     * 
     * @endpoint get /api/v1/notifications/unread-count
*/
    getUnreadNotificationCount(extraHttpRequestParams?: any): Observable<UnreadNotificationCount>;

    /**
     * The caller\&#39;s notifications (newest first)
     * Cursor-paginated, newest first; &#x60;unreadOnly&#x3D;true&#x60; lists unread ones only. Notifications whose in-app channel was disabled by the caller\&#39;s preferences are never listed.
     * @endpoint get /api/v1/notifications
* @param requestParameters
     */
    listNotifications(requestParameters: ListNotificationsRequestParams, extraHttpRequestParams?: any): Observable<CursorPageNotificationResponse>;

    /**
     * Mark every notification read
     * 
     * @endpoint post /api/v1/notifications/read-all
*/
    markAllNotificationsRead(extraHttpRequestParams?: any): Observable<ReadAllNotificationsResponse>;

    /**
     * Mark one notification read
     * Idempotent: the first read time is kept.
     * @endpoint post /api/v1/notifications/{id}/read
* @param requestParameters
     */
    markNotificationRead(requestParameters: MarkNotificationReadRequestParams, extraHttpRequestParams?: any): Observable<NotificationResponse>;

    /**
     * Register a device push token
     * Idempotent. A token registered by another account moves to the caller; an invalidated token becomes valid again.
     * @endpoint post /api/v1/me/push-tokens
* @param requestParameters
     */
    registerPushToken(requestParameters: RegisterPushTokenRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
