/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AvatarResponse } from '../model/models';
import { MyProfileResponse } from '../model/models';
import { ProblemDetail } from '../model/models';
import { TagResponse } from '../model/models';
import { UpdateProfileRequest } from '../model/models';
import { UpdateProfileTagsRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface SearchTagsRequestParams {
    query?: string;
    category?: 'GAME' | 'ROLE' | 'STYLE' | 'LOGISTICS' | 'LANGUAGE' | 'CUSTOM';
    limit?: number;
}

export interface UpdateMyProfileRequestParams {
    updateProfileRequest: UpdateProfileRequest;
}

export interface UpdateMyProfileTagsRequestParams {
    updateProfileTagsRequest: UpdateProfileTagsRequest;
}

export interface UploadMyAvatarRequestParams {
    file: Blob;
}


export interface ProfileServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Remove the caller\&#39;s avatar
     * 
     * @endpoint delete /api/v1/me/profile/avatar
*/
    deleteMyAvatar(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * The caller\&#39;s profile
     * Returns defaults derived from the account (handle, display name) until the profile is saved for the first time.
     * @endpoint get /api/v1/me/profile
*/
    getMyProfile(extraHttpRequestParams?: any): Observable<MyProfileResponse>;

    /**
     * Search profile tags
     * Active tags whose label or slug contains &#x60;query&#x60; (case and accent insensitive), prefix matches first, then the most used. Without &#x60;query&#x60;: the most used tags. Rate-limited (60 per minute).
     * @endpoint get /api/v1/tags
* @param requestParameters
     */
    searchTags(requestParameters: SearchTagsRequestParams, extraHttpRequestParams?: any): Observable<Array<TagResponse>>;

    /**
     * Save the caller\&#39;s profile
     * Full replacement of handle, display name, bio, games and languages. 400 for unknown games (yugioh, pokemon, mtg, riftbound), non ISO 639-1 languages or blocked terms; 409 HANDLE_TAKEN when the handle is used (case-insensitive) or reserved. The first save completes the &#x60;profileComplete&#x60; onboarding step.
     * @endpoint put /api/v1/me/profile
* @param requestParameters
     */
    updateMyProfile(requestParameters: UpdateMyProfileRequestParams, extraHttpRequestParams?: any): Observable<MyProfileResponse>;

    /**
     * Replace the caller\&#39;s profile tags
     * At most 12 tags in total. &#x60;tagIds&#x60; must be active tags; &#x60;customLabels&#x60; (2-24 characters) are checked against the banned-term rules and created as CUSTOM tags (or matched to an existing tag with the same slug). Returns the resulting tags.
     * @endpoint put /api/v1/me/profile/tags
* @param requestParameters
     */
    updateMyProfileTags(requestParameters: UpdateMyProfileTagsRequestParams, extraHttpRequestParams?: any): Observable<Array<TagResponse>>;

    /**
     * Upload the caller\&#39;s avatar
     * Multipart part &#x60;file&#x60;: JPEG, PNG or WebP up to 5 MB (type sniffed from the content). The server cover-crops it to a 512x512 square and re-encodes it without any metadata (EXIF/GPS stripped). 413 above 5 MB, 415 for other types, 400 for unreadable images. Rate-limited (10 per hour).
     * @endpoint post /api/v1/me/profile/avatar
* @param requestParameters
     */
    uploadMyAvatar(requestParameters: UploadMyAvatarRequestParams, extraHttpRequestParams?: any): Observable<AvatarResponse>;

}
