/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProblemDetail } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetPlaceholderImageRequestParams {
    game: string;
    file: string;
    ifNoneMatch?: string;
}

export interface GetPublicMediaRequestParams {
    key: string;
}


export interface PublicServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Card placeholder image (SVG)
     * &#x60;file&#x60; is &#x60;&lt;card slug&gt;.svg&#x60;. Generated on the server from the card name; no scripts or external references. Public cache for a day, ETag.
     * @endpoint get /api/v1/public/placeholder-images/{game}/{file}
* @param requestParameters
     */
    getPlaceholderImage(requestParameters: GetPlaceholderImageRequestParams, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * Stored media (avatars)
     * Serves an object of the media storage by key (for example &#x60;avatars/&lt;user id&gt;/&lt;random&gt;.jpg&#x60;). Immutable: cache for a year.
     * @endpoint get /api/v1/public/media/{key}
* @param requestParameters
     */
    getPublicMedia(requestParameters: GetPublicMediaRequestParams, extraHttpRequestParams?: any): Observable<Blob>;

}
