/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PageResponsePublicInventoryItem } from '../model/models';
import { ProblemDetail } from '../model/models';
import { PublicBinderResponse } from '../model/models';
import { PublicBinderSummary } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetPublicBinderRequestParams {
    id: string;
}

export interface ListCollectorBindersRequestParams {
    handle: string;
}

export interface ListCollectorInventoryRequestParams {
    handle: string;
    game?: string;
    query?: string;
    availability?: 'COLLECTION_ONLY' | 'TRADE' | 'SALE' | 'TRADE_OR_SALE' | 'NOT_AVAILABLE';
    page?: number;
    size?: number;
}

export interface ListPublicBinderItemsRequestParams {
    id: string;
    game?: string;
    query?: string;
    availability?: 'COLLECTION_ONLY' | 'TRADE' | 'SALE' | 'TRADE_OR_SALE' | 'NOT_AVAILABLE';
    page?: number;
    size?: number;
}


export interface PublicBindersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * A public binder (auth optional)
     * 404 unless the binder is public right now (visibility, expiry, freshness, the owner\&#39;s account state and privacy settings). The owner block carries a region label and, for signed-in callers with a trading area, a distance bucket; never coordinates. Signed-in callers other than the owner consume &#x60;binder.views.per_day&#x60; once per binder and UTC day (429 LIMIT_REACHED beyond the plan limit).
     * @endpoint get /api/v1/public/binders/{id}
* @param requestParameters
     */
    getPublicBinder(requestParameters: GetPublicBinderRequestParams, extraHttpRequestParams?: any): Observable<PublicBinderResponse>;

    /**
     * Public binders of a collector (auth optional)
     * Only binders that are public right now and hold at least one public item, in the owner\&#39;s order. 404 when the collector is suspended, pending deletion, deleted, has a PRIVATE profile or a block exists. Empty when the collector is neither discoverable nor has a PUBLIC profile.
     * @endpoint get /api/v1/collectors/{handle}/binders
* @param requestParameters
     */
    listCollectorBinders(requestParameters: ListCollectorBindersRequestParams, extraHttpRequestParams?: any): Observable<Array<PublicBinderSummary>>;

    /**
     * Public items of a collector across binders (auth optional)
     * Only items that are public right now, by card name. 404 when the collector is suspended, pending deletion, deleted, has a PRIVATE profile or a block exists. Never private notes or coordinates.
     * @endpoint get /api/v1/collectors/{handle}/inventory
* @param requestParameters
     */
    listCollectorInventory(requestParameters: ListCollectorInventoryRequestParams, extraHttpRequestParams?: any): Observable<PageResponsePublicInventoryItem>;

    /**
     * Public items of a public binder (auth optional)
     * 404 unless the binder is public right now. Only items that are public right now, by card name. Never private notes or coordinates.
     * @endpoint get /api/v1/public/binders/{id}/items
* @param requestParameters
     */
    listPublicBinderItems(requestParameters: ListPublicBinderItemsRequestParams, extraHttpRequestParams?: any): Observable<PageResponsePublicInventoryItem>;

}
