/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { MyReport } from '../model/models';
import { ProblemDetail } from '../model/models';
import { ReportCollectorRequest } from '../model/models';
import { ReportConfirmation } from '../model/models';
import { ReportReasonOption } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ReportCollectorRequestParams {
    reportCollectorRequest: ReportCollectorRequest;
    idempotencyKey?: string;
}


export interface ReportsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * The caller\&#39;s reports (status only)
     * Newest first, at most 100. Moderator notes and decisions stay private; the reporter only sees the status.
     * @endpoint get /api/v1/me/reports
*/
    listMyReports(extraHttpRequestParams?: any): Observable<Array<MyReport>>;

    /**
     * Reasons for reporting a collector
     * In the order the report dialog shows them.
     * @endpoint get /api/v1/public/report-reasons
*/
    listReportReasons(extraHttpRequestParams?: any): Observable<Array<ReportReasonOption>>;

    /**
     * Report a collector
     * A reason is required; details at most 1000 characters. The context says where the report was made (PROFILE by default; CONVERSATION needs a conversation between the caller and the collector, POST one of their community posts, BINDER one of their binders; 400 otherwise). 422 CANNOT_REPORT_SELF, 404 unknown collector, 409 REPORT_ALREADY_OPEN (extension reportId) while the caller\&#39;s previous report against the collector is open, 429 RATE_LIMITED beyond 5 reports per day. An Idempotency-Key repeats the original answer for 24 hours. Open reports from 3 distinct reporters within 7 days flag the collector for review and pause their public listings pending review (never a ban).
     * @endpoint post /api/v1/reports/collectors
* @param requestParameters
     */
    reportCollector(requestParameters: ReportCollectorRequestParams, extraHttpRequestParams?: any): Observable<ReportConfirmation>;

}
