/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { NotificationSettingsRequest } from '../model/models';
import { NotificationSettingsResponse } from '../model/models';
import { PrivacySettings } from '../model/models';
import { ProblemDetail } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface UpdateNotificationSettingsRequestParams {
    notificationSettingsRequest: NotificationSettingsRequest;
}

export interface UpdatePrivacySettingsRequestParams {
    privacySettings: PrivacySettings;
}


export interface SettingsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * The caller\&#39;s notification preferences
     * Defaults: push and in-app on, email off, MARKETING fully off, wishlist alerts on.
     * @endpoint get /api/v1/me/settings/notifications
*/
    getNotificationSettings(extraHttpRequestParams?: any): Observable<NotificationSettingsResponse>;

    /**
     * The caller\&#39;s privacy settings
     * Defaults favour safety: not discoverable, online status hidden, profile visible to members, messages from members with a profile, wishlist hidden.
     * @endpoint get /api/v1/me/settings/privacy
*/
    getPrivacySettings(extraHttpRequestParams?: any): Observable<PrivacySettings>;

    /**
     * Replace the caller\&#39;s notification preferences
     * Full replacement. Unknown categories, malformed times (HH:mm) and unknown time zones are 400.
     * @endpoint put /api/v1/me/settings/notifications
* @param requestParameters
     */
    updateNotificationSettings(requestParameters: UpdateNotificationSettingsRequestParams, extraHttpRequestParams?: any): Observable<NotificationSettingsResponse>;

    /**
     * Replace the caller\&#39;s privacy settings
     * Full replacement (every field required). &#x60;discoverable&#x60; lists the collector (state/province + country, never the city) in region search, card holder lists and the map\&#39;s state binder lists; switching it on needs the 18+ confirmation (403 AGE_CONFIRMATION_REQUIRED) and a country and state/province (&#x60;PUT /me/location&#x60;, 409 LOCATION_REQUIRED); switching it off removes the collector immediately.
     * @endpoint put /api/v1/me/settings/privacy
* @param requestParameters
     */
    updatePrivacySettings(requestParameters: UpdatePrivacySettingsRequestParams, extraHttpRequestParams?: any): Observable<PrivacySettings>;

}
