/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateWishlistItemRequest } from '../model/models';
import { CursorPageWishlistMatchResponse } from '../model/models';
import { ProblemDetail } from '../model/models';
import { UpdateWishlistItemRequest } from '../model/models';
import { WishlistItemResponse } from '../model/models';
import { WishlistSummaryEntry } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateWishlistItemRequestParams {
    createWishlistItemRequest: CreateWishlistItemRequest;
}

export interface DeleteWishlistItemRequestParams {
    id: string;
}

export interface DismissWishlistMatchRequestParams {
    id: string;
}

export interface GetCollectorWishlistRequestParams {
    handle: string;
}

export interface ListWishlistMatchesRequestParams {
    id: string;
    cursor?: string;
    limit?: number;
    includeDismissed?: boolean;
}

export interface UpdateWishlistItemRequestParams {
    id: string;
    updateWishlistItemRequest: UpdateWishlistItemRequest;
}


export interface WishlistServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Add a card to the wishlist
     * cardId (any printing) or printingId is required. The new item is matched at once against the public inventory nearby (no notification; see matchCount and GET /wishlist/{id}/matches); later publications notify (WISHLIST_MATCH). 409 CONFLICT for an identical wish; 429 LIMIT_REACHED beyond wishlist.items.max (FREE 20, PREMIUM 500) or a radius beyond map.radius.max_km.
     * @endpoint post /api/v1/wishlist
* @param requestParameters
     */
    createWishlistItem(requestParameters: CreateWishlistItemRequestParams, extraHttpRequestParams?: any): Observable<WishlistItemResponse>;

    /**
     * Remove a wishlist item
     * Its matches are removed with it.
     * @endpoint delete /api/v1/wishlist/{id}
* @param requestParameters
     */
    deleteWishlistItem(requestParameters: DeleteWishlistItemRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Dismiss a match
     * Idempotent; a dismissed match never comes back for this wishlist item.
     * @endpoint post /api/v1/wishlist/matches/{id}/dismiss
* @param requestParameters
     */
    dismissWishlistMatch(requestParameters: DismissWishlistMatchRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * A collector\&#39;s public wishlist
     * Only when the collector shows their wishlist (privacy setting wishlistVisible) and their profile is visible to the caller: the active items as card, printing and minimum condition (never notes, prices or radii). 404 otherwise, and for unknown, suspended, deleted or blocked collectors.
     * @endpoint get /api/v1/collectors/{handle}/wishlist
* @param requestParameters
     */
    getCollectorWishlist(requestParameters: GetCollectorWishlistRequestParams, extraHttpRequestParams?: any): Observable<Array<WishlistSummaryEntry>>;

    /**
     * The caller\&#39;s wishlist items (newest first)
     * 
     * @endpoint get /api/v1/wishlist
*/
    listWishlist(extraHttpRequestParams?: any): Observable<Array<WishlistItemResponse>>;

    /**
     * Public items matching a wishlist item (newest first)
     * Cursor-paginated. Each match carries the public item (never private notes), the owner\&#39;s map marker at the derived public point and the distance bucket between the two collectors\&#39; public points. Items that stopped being public and collectors blocked in either direction are left out; dismissed matches only with includeDismissed&#x3D;true.
     * @endpoint get /api/v1/wishlist/{id}/matches
* @param requestParameters
     */
    listWishlistMatches(requestParameters: ListWishlistMatchesRequestParams, extraHttpRequestParams?: any): Observable<CursorPageWishlistMatchResponse>;

    /**
     * Update a wishlist item (any subset of the fields)
     * Absent fields are unchanged. Changing the criteria re-matches the item (dismissed matches stay dismissed).
     * @endpoint patch /api/v1/wishlist/{id}
* @param requestParameters
     */
    updateWishlistItem(requestParameters: UpdateWishlistItemRequestParams, extraHttpRequestParams?: any): Observable<WishlistItemResponse>;

}
