#!/usr/bin/env node
/**
 * Builds `dist/tokens.css` and `dist/tokens.ts` from `tokens.json`.
 *
 *   node build.mjs           # write dist/
 *   node build.mjs --check   # exit 1 if dist/ is missing or out of date (CI)
 *
 * No dependencies: Node >= 20 only.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, 'tokens.json');
const distDir = join(here, 'dist');
const check = process.argv.includes('--check');

const tokens = JSON.parse(await readFile(src, 'utf8'));

/** Groups whose numeric values are pixel lengths. */
const PX_GROUPS = new Set(['fontSize', 'spacing', 'radius', 'breakpoint', 'focus']);

const kebab = (s) =>
  s
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .toLowerCase();

function cssValue(group, value) {
  if (typeof value === 'number') {
    return PX_GROUPS.has(group) ? `${value}px` : String(value);
  }
  return String(value);
}

/** Flattens a nested object into [path[], value] pairs (leaves only). */
function leaves(obj, path = []) {
  const out = [];
  for (const [key, value] of Object.entries(obj)) {
    if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
      out.push(...leaves(value, [...path, key]));
    } else {
      out.push([[...path, key], value]);
    }
  }
  return out;
}

function declarations(group, obj) {
  return leaves(obj).map(([path, value]) => {
    const name = `--${[kebab(group), ...path.map(kebab)].join('-')}`;
    return `  ${name}: ${cssValue(group, value)};`;
  });
}

// ---------------------------------------------------------------- tokens.css
const base = [];
for (const [group, value] of Object.entries(tokens)) {
  if (group.startsWith('$') || group === 'color') continue;
  if (group === 'font') {
    for (const [name, def] of Object.entries(value)) {
      base.push(`  --font-${kebab(name)}: ${def.web};`);
    }
    continue;
  }
  base.push(...declarations(group, value));
}
const light = declarations('color', tokens.color.light);
const dark = declarations('color', tokens.color.dark);
const indent = (lines) => lines.map((l) => `  ${l}`);

const css = `/* Generated by packages/design-tokens/build.mjs from tokens.json. Do not edit. */
:root {
  color-scheme: light;
${base.join('\n')}
${light.join('\n')}
}

[data-theme="dark"] {
  color-scheme: dark;
${dark.join('\n')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${indent(dark).join('\n')}
  }
}
`;

// ----------------------------------------------------------------- tokens.ts
const { $meta, color, ...rest } = tokens;
const ts = `/* Generated by packages/design-tokens/build.mjs from tokens.json. Do not edit. */
/* eslint-disable */

export const meta = ${JSON.stringify($meta, null, 2)} as const;

export const lightColors = ${JSON.stringify(color.light, null, 2)} as const;

export const darkColors = ${JSON.stringify(color.dark, null, 2)} as const;

export const colors = { light: lightColors, dark: darkColors } as const;

export const tokens = ${JSON.stringify(rest, null, 2)} as const;

/** A resolved colour scheme. */
export type Theme = 'light' | 'dark';
/** What the user asked for; 'system' follows prefers-color-scheme. */
export type ThemePreference = Theme | 'system';
export const THEMES: readonly Theme[] = ['light', 'dark'];
export const THEME_PREFERENCES: readonly ThemePreference[] = ['light', 'dark', 'system'];

export type ColorTokens = typeof lightColors;
export type ColorToken = keyof ColorTokens;
export type StatusToken = keyof ColorTokens['status'];
export type AvailabilityToken = keyof ColorTokens['availability'];
export type OnlineToken = keyof ColorTokens['online'];
export type FontToken = keyof typeof tokens.font;
export type FontSizeToken = keyof typeof tokens.fontSize;
export type SpacingToken = keyof typeof tokens.spacing;
export type RadiusToken = keyof typeof tokens.radius;
export type BreakpointToken = keyof typeof tokens.breakpoint;

export const breakpoints = tokens.breakpoint;
export const spacing = tokens.spacing;
export const radius = tokens.radius;
export const fontSize = tokens.fontSize;
export const fonts = tokens.font;

/** Resolves a theme preference against the platform colour scheme. */
export function resolveTheme(preference: ThemePreference, prefersDark: boolean): Theme {
  return preference === 'system' ? (prefersDark ? 'dark' : 'light') : preference;
}

/** Returns the colour tokens for a theme. */
export function colorsFor(theme: Theme): ColorTokens {
  return colors[theme];
}

/** Builds the CSS custom property name used in tokens.css: cssVar('color', 'status', 'fresh') === '--color-status-fresh'. */
export function cssVar(...path: string[]): string {
  const kebab = (s: string) =>
    s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/[^a-zA-Z0-9]+/g, '-').toLowerCase();
  return '--' + path.map(kebab).join('-');
}
`;

const outputs = {
  [join(distDir, 'tokens.css')]: css,
  [join(distDir, 'tokens.ts')]: ts,
};

if (check) {
  let stale = false;
  for (const [file, content] of Object.entries(outputs)) {
    if (!existsSync(file) || (await readFile(file, 'utf8')) !== content) {
      console.error(`stale: ${file}`);
      stale = true;
    }
  }
  if (stale) {
    console.error('design-tokens: dist/ is out of date. Run `npm run build`.');
    process.exit(1);
  }
  console.log('design-tokens: dist/ is up to date.');
} else {
  await mkdir(distDir, { recursive: true });
  for (const [file, content] of Object.entries(outputs)) {
    await writeFile(file, content, 'utf8');
    console.log(`wrote ${file}`);
  }
}
