#!/usr/bin/env node
/**
 * Copies the legal document texts of the web app into `src/legal/` so the mobile app renders
 * exactly the same versioned drafts in-app, in both languages:
 *   apps/web-angular/src/app/features/legal/legal-content.ts    → src/legal/legalContent.ts
 *   apps/web-angular/src/app/features/legal/legal-content.fr.ts → src/legal/legalContent.fr.ts
 * Both web files are plain TypeScript without Angular imports; the French file's type import of
 * `./legal-content` is rewritten to the mobile file name. The API serves the document list
 * (type, version, title, web path); the texts live with the clients.
 *
 * Usage: `npm run sync:legal` (writes) or `npm run sync:legal -- --check` (exit 1 when stale).
 * `__tests__/screens/legal.test.tsx` fails as well when a copy drifts from its web file.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(here, '..');
const webLegalDir = resolve(projectRoot, '../web-angular/src/app/features/legal');
const mobileLegalDir = resolve(projectRoot, 'src/legal');

function header(sourceName) {
  return (
    `// GENERATED by \`npm run sync:legal\` from apps/web-angular/src/app/features/legal/${sourceName}.\n` +
    '// Do not edit here: change the web file, then run `npm run sync:legal` in apps/mobile.\n' +
    '/* eslint-disable */\n'
  );
}

/** The mobile copy of a web legal file: the header, then the web source (LF line endings). */
export function render(webSource, sourceName = 'legal-content.ts') {
  const body = webSource.replace(/\r\n/g, '\n');
  return (
    header(sourceName) +
    (sourceName === 'legal-content.fr.ts'
      ? body.replace("from './legal-content'", "from './legalContent'")
      : body)
  );
}

export const FILES = [
  { source: 'legal-content.ts', target: 'legalContent.ts' },
  { source: 'legal-content.fr.ts', target: 'legalContent.fr.ts' },
];

const check = process.argv.includes('--check');
let stale = false;
for (const file of FILES) {
  const source = resolve(webLegalDir, file.source);
  const target = resolve(mobileLegalDir, file.target);
  if (!existsSync(source)) {
    console.error(`[sync-legal] ${source} not found.`);
    process.exit(1);
  }
  const expected = render(readFileSync(source, 'utf8'), file.source);
  const current = existsSync(target) ? readFileSync(target, 'utf8').replace(/\r\n/g, '\n') : null;
  if (current === expected) {
    console.log(`[sync-legal] src/legal/${file.target} up to date.`);
  } else if (check) {
    console.error(`[sync-legal] src/legal/${file.target} is stale. Run \`npm run sync:legal\`.`);
    stale = true;
  } else {
    writeFileSync(target, expected);
    console.log(`[sync-legal] wrote ${target}`);
  }
}
if (stale) {
  process.exit(1);
}
