#!/usr/bin/env node
/**
 * Copies the legal document texts of the web app (apps/web-angular/src/app/features/legal/
 * legal-content.ts, plain TypeScript without Angular imports) into `src/legal/legalContent.ts`
 * so the mobile app renders exactly the same versioned drafts in-app. The API serves the
 * document list (type, version, title, web path); the texts live with the clients.
 *
 * Usage: `npm run sync:legal` (writes) or `npm run sync:legal -- --check` (exit 1 when stale).
 * `__tests__/screens/legal.test.tsx` fails as well when the copy drifts from the web file.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(here, '..');
const source = resolve(projectRoot, '../web-angular/src/app/features/legal/legal-content.ts');
const target = resolve(projectRoot, 'src/legal/legalContent.ts');

export const HEADER =
  '// GENERATED by `npm run sync:legal` from apps/web-angular/src/app/features/legal/legal-content.ts.\n' +
  '// Do not edit here: change the web file, then run `npm run sync:legal` in apps/mobile.\n' +
  '/* eslint-disable */\n';

export function render(webSource) {
  return HEADER + webSource.replace(/\r\n/g, '\n');
}

if (!existsSync(source)) {
  console.error(`[sync-legal] ${source} not found.`);
  process.exit(1);
}
const expected = render(readFileSync(source, 'utf8'));
const current = existsSync(target) ? readFileSync(target, 'utf8').replace(/\r\n/g, '\n') : null;

if (process.argv.includes('--check')) {
  if (current !== expected) {
    console.error('[sync-legal] src/legal/legalContent.ts is stale. Run `npm run sync:legal`.');
    process.exit(1);
  }
  console.log('[sync-legal] up to date.');
} else if (current === expected) {
  console.log('[sync-legal] already up to date.');
} else {
  writeFileSync(target, expected);
  console.log(`[sync-legal] wrote ${target}`);
}
