-- V106: platform regions instead of geolocation (ADR 0017, owner decision 2026-10-08).
--
-- Reference data of the location module: the three platform regions, the countries mapped to
-- them (ISO 3166-1 alpha-2) and the first-level subdivisions collectors choose from (ISO 3166-2;
-- a country without usable subdivisions has one pseudo-subdivision coded with its alpha-2 code,
-- whole_country = true). Seeded by V107 (generated by scripts/regions/build.mjs, the same rules
-- that build the web map's boundary assets, so the codes match). Admins move a country to another
-- region or deactivate it through /admin/regions (audited); the lists are cached in Redis.
-- No coordinate, geometry or geography column anywhere: the map's boundaries are static web assets.

CREATE TABLE platform_region (
    code       text        PRIMARY KEY,
    name       text        NOT NULL,
    sort_order integer     NOT NULL DEFAULT 0,
    is_default boolean     NOT NULL DEFAULT false,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_platform_region_code CHECK (code ~ '^[a-z]+(-[a-z]+)*$' AND char_length(code) <= 32),
    CONSTRAINT ck_platform_region_name CHECK (char_length(name) BETWEEN 1 AND 80)
);

-- At most one default region (the signed-out default and the fallback of every scoped search).
CREATE UNIQUE INDEX uq_platform_region_default ON platform_region (is_default) WHERE is_default;

COMMENT ON TABLE platform_region IS 'Platform regions (ADR 0017): every scoped API call names one; never used for authorization.';

CREATE TABLE country (
    code        text        PRIMARY KEY,
    name        text        NOT NULL,
    region_code text        NOT NULL REFERENCES platform_region (code) ON UPDATE CASCADE,
    active      boolean     NOT NULL DEFAULT true,
    sort_order  integer     NOT NULL DEFAULT 0,
    updated_by  uuid        REFERENCES user_account (id) ON DELETE SET NULL,
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_country_code CHECK (code ~ '^[A-Z]{2}$'),
    CONSTRAINT ck_country_name CHECK (char_length(name) BETWEEN 1 AND 80)
);

CREATE INDEX ix_country_region ON country (region_code);

COMMENT ON TABLE country IS 'Countries (ISO 3166-1 alpha-2; XK user-assigned for Kosovo) and their platform region (ADR 0017). Inactive countries cannot be chosen any more; existing locations keep them.';
COMMENT ON COLUMN country.region_code IS 'Editable through PUT /api/v1/admin/regions/countries/{code} (audited). The map draws a country only in the boundary asset of the region it was seeded in.';

CREATE TABLE subdivision (
    code          text    PRIMARY KEY,
    country_code  text    NOT NULL REFERENCES country (code) ON UPDATE CASCADE,
    name          text    NOT NULL,
    whole_country boolean NOT NULL DEFAULT false,
    CONSTRAINT uq_subdivision_country_code UNIQUE (country_code, code),
    CONSTRAINT ck_subdivision_code CHECK (code ~ '^[A-Z]{2}(-[A-Z0-9]{1,3})?$'),
    CONSTRAINT ck_subdivision_country CHECK (code = country_code OR code LIKE country_code || '-%'),
    CONSTRAINT ck_subdivision_whole CHECK (whole_country = (code = country_code)),
    CONSTRAINT ck_subdivision_name CHECK (char_length(name) BETWEEN 1 AND 120)
);

COMMENT ON TABLE subdivision IS 'First-level subdivisions (ISO 3166-2) collectors choose as their state/province (ADR 0017); the codes of the web boundary assets.';
COMMENT ON COLUMN subdivision.whole_country IS 'Pseudo-subdivision covering a whole country without usable ISO 3166-2 units; its code is the alpha-2 code and labels show the country only.';
