/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AcceptOfferRequest { 
    /**
     * The version the caller saw (409 STALE_OFFER when it changed)
     */
    version?: number;
}

