/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountDeletionJobResponse { 
    /**
     * Accounts deleted
     */
    processed: number;
    /**
     * Due requests cancelled or taken meanwhile
     */
    skipped: number;
    /**
     * Requests left pending after an error
     */
    failed: number;
}

