/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A sponsored placement (always labelled Sponsored)
 */
export interface Ad { 
    creativeId?: string;
    placement?: AdPlacementEnum;
    sponsored?: boolean;
    label?: string;
    advertiser?: string;
    headline?: string;
    body?: string;
    imageUrl?: string;
    ctaLabel?: string;
    clickUrl?: string;
    impressionToken?: string;
}
export enum AdPlacementEnum {
    SearchSponsored = 'SEARCH_SPONSORED',
    MapPanel = 'MAP_PANEL',
    InventorySidebar = 'INVENTORY_SIDEBAR',
    CollectorProfile = 'COLLECTOR_PROFILE',
    MobileFeed = 'MOBILE_FEED'
};



