/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdCampaignRequest { 
    advertiserId: string;
    name: string;
    /**
     * DRAFT (default), ACTIVE, PAUSED or ENDED
     */
    status?: AdCampaignRequestStatusEnum;
    startAt: string;
    endAt?: string;
    budgetTotal: number;
    budgetDaily?: number;
    currency: string;
    pricing: AdCampaignRequestPricingEnum;
    /**
     * CPM: per 1000 impressions; CPC: per click; ignored for FLAT
     */
    bidAmount?: number;
    priority?: number;
    frequencyCapPerDay?: number;
}
export enum AdCampaignRequestStatusEnum {
    Draft = 'DRAFT',
    Active = 'ACTIVE',
    Paused = 'PAUSED',
    Ended = 'ENDED'
};
export enum AdCampaignRequestPricingEnum {
    Cpm = 'CPM',
    Cpc = 'CPC',
    Flat = 'FLAT'
};



