/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdDeliveryTotals } from './adDeliveryTotals';
import { AdDailyStats } from './adDailyStats';


/**
 * Delivery statistics of a campaign
 */
export interface AdCampaignStats { 
    campaignId?: string;
    status?: AdCampaignStatsStatusEnum;
    pricing?: AdCampaignStatsPricingEnum;
    currency?: string;
    budgetTotal?: number;
    spent?: number;
    remainingBudget?: number;
    totals?: AdDeliveryTotals;
    from?: string;
    to?: string;
    daily?: Array<AdDailyStats>;
}
export enum AdCampaignStatsStatusEnum {
    Draft = 'DRAFT',
    Active = 'ACTIVE',
    Paused = 'PAUSED',
    Ended = 'ENDED'
};
export enum AdCampaignStatsPricingEnum {
    Cpm = 'CPM',
    Cpc = 'CPC',
    Flat = 'FLAT'
};



