/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdCreativeRequest { 
    placement: AdCreativeRequestPlacementEnum;
    headline: string;
    body?: string;
    /**
     * https URL or site path
     */
    imageUrl?: string;
    ctaLabel: string;
    /**
     * https URL or site path
     */
    landingUrl: string;
    /**
     * DRAFT (default), ACTIVE, PAUSED or ARCHIVED
     */
    status?: AdCreativeRequestStatusEnum;
}
export enum AdCreativeRequestPlacementEnum {
    SearchSponsored = 'SEARCH_SPONSORED',
    MapPanel = 'MAP_PANEL',
    InventorySidebar = 'INVENTORY_SIDEBAR',
    CollectorProfile = 'COLLECTOR_PROFILE',
    MobileFeed = 'MOBILE_FEED'
};
export enum AdCreativeRequestStatusEnum {
    Draft = 'DRAFT',
    Active = 'ACTIVE',
    Paused = 'PAUSED',
    Archived = 'ARCHIVED'
};



