/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminCreditGrantRequest { 
    userId: string;
    /**
     * Positive: GRANT; negative: ADJUST (never below a balance of 0); never 0
     */
    amount: number;
    reason: AdminCreditGrantRequestReasonEnum;
    /**
     * Internal note (admin views only)
     */
    note?: string;
}
export enum AdminCreditGrantRequestReasonEnum {
    Admin = 'ADMIN',
    Promo = 'PROMO',
    Reward = 'REWARD',
    Correction = 'CORRECTION'
};



