/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An ad creative (admin view)
 */
export interface AdminAdCreative { 
    id?: string;
    campaignId?: string;
    placement?: AdminAdCreativePlacementEnum;
    headline?: string;
    body?: string;
    imageUrl?: string;
    ctaLabel?: string;
    landingUrl?: string;
    status?: AdminAdCreativeStatusEnum;
    createdAt?: string;
    updatedAt?: string;
}
export enum AdminAdCreativePlacementEnum {
    SearchSponsored = 'SEARCH_SPONSORED',
    MapPanel = 'MAP_PANEL',
    InventorySidebar = 'INVENTORY_SIDEBAR',
    CollectorProfile = 'COLLECTOR_PROFILE',
    MobileFeed = 'MOBILE_FEED'
};
export enum AdminAdCreativeStatusEnum {
    Draft = 'DRAFT',
    Active = 'ACTIVE',
    Paused = 'PAUSED',
    Archived = 'ARCHIVED'
};



