/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminSubscription } from './adminSubscription';
import { AdminSubscriptionEvent } from './adminSubscriptionEvent';
import { AdminBillingWebhook } from './adminBillingWebhook';


/**
 * A subscription with its history
 */
export interface AdminSubscriptionDetail { 
    subscription?: AdminSubscription;
    events?: Array<AdminSubscriptionEvent>;
    webhooks?: Array<AdminBillingWebhook>;
}

