/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentWebhookEvent } from './paymentWebhookEvent';
import { ModerationHistory } from './moderationHistory';
import { DisputeNote } from './disputeNote';
import { TradeEvent } from './tradeEvent';
import { Dispute } from './dispute';
import { PaymentEvent } from './paymentEvent';
import { DisputePartyRatings } from './disputePartyRatings';
import { PaymentRefund } from './paymentRefund';


/**
 * A dispute with its full history (admin)
 */
export interface AdminDispute { 
    dispute: Dispute;
    /**
     * Internal admin notes (never shown to the parties)
     */
    internalNotes: Array<DisputeNote>;
    tradeTimeline: Array<TradeEvent>;
    paymentEvents: Array<PaymentEvent>;
    refunds: Array<PaymentRefund>;
    webhooks: Array<PaymentWebhookEvent>;
    buyerHistory: ModerationHistory;
    sellerHistory: ModerationHistory;
    buyerRatings: DisputePartyRatings;
    sellerRatings: DisputePartyRatings;
}

