/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Card creation or change
 */
export interface AdminCardRequest { 
    gameSlug?: string;
    name: string;
    cardType?: string;
    subtype?: string;
    text?: string;
    metadata?: { [key: string]: any | null; };
}

