/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Account as listed in the admin console
 */
export interface AdminUserSummary { 
    id: string;
    handle: string;
    displayName?: string | null;
    email?: string | null;
    emailVerified: boolean;
    status: AdminUserSummaryStatusEnum;
    roles: Set<AdminUserSummaryRolesEnum>;
    plan: string;
    avatarUrl?: string | null;
    createdAt: string;
    lastActiveAt?: string | null;
    suspendedUntil?: string | null;
}
export enum AdminUserSummaryStatusEnum {
    Active = 'ACTIVE',
    Suspended = 'SUSPENDED',
    DeletionRequested = 'DELETION_REQUESTED',
    Deleted = 'DELETED'
};
export enum AdminUserSummaryRolesEnum {
    User = 'USER',
    PremiumUser = 'PREMIUM_USER',
    Moderator = 'MODERATOR',
    Admin = 'ADMIN',
    SuperAdmin = 'SUPER_ADMIN'
};



