/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminSubscriptionCancelRequest { 
    /**
     * true: ends now; false (default): at the period end
     */
    immediately?: boolean;
    /**
     * Internal reason (not stored in the audit log)
     */
    reason?: string;
}

