/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A donation (admin view)
 */
export interface AdminDonation { 
    id?: string;
    userId?: string;
    amount?: number;
    currency?: string;
    provider?: string;
    status?: AdminDonationStatusEnum;
    message?: string;
    publicThanks?: boolean;
    failureCode?: string;
    createdAt?: string;
    succeededAt?: string;
    refundedAt?: string;
}
export enum AdminDonationStatusEnum {
    Pending = 'PENDING',
    Succeeded = 'SUCCEEDED',
    Failed = 'FAILED',
    Refunded = 'REFUNDED'
};



