/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Usage limit of a plan (admin view)
 */
export interface AdminUsageLimit { 
    id?: string;
    planCode?: string;
    key?: string;
    kind?: AdminUsageLimitKindEnum;
    window?: AdminUsageLimitWindowEnum;
    /**
     * null means unlimited
     */
    maxValue?: number;
    unlimited?: boolean;
    description?: string;
    updatedBy?: string;
    updatedAt?: string;
}
export enum AdminUsageLimitKindEnum {
    Counter = 'COUNTER',
    Cap = 'CAP'
};
export enum AdminUsageLimitWindowEnum {
    Day = 'DAY',
    Month = 'MONTH',
    Total = 'TOTAL'
};



