/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DonationTotal } from './donationTotal';
import { PageResponseAdminDonation } from './pageResponseAdminDonation';


/**
 * Donations with totals (admin)
 */
export interface AdminDonations { 
    donations?: PageResponseAdminDonation;
    totals?: Array<DonationTotal>;
}

