/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlanFeature } from './planFeature';
import { UsageLimit } from './usageLimit';


/**
 * Plan with features and limits (admin view)
 */
export interface AdminPlan { 
    id?: string;
    code?: string;
    name?: string;
    description?: string;
    monthlyPrice?: number;
    currency?: string;
    active?: boolean;
    sortOrder?: number;
    features?: Array<PlanFeature>;
    limits?: Array<UsageLimit>;
    updatedBy?: string;
    updatedAt?: string;
}

