/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A donation webhook (admin)
 */
export interface AdminDonationWebhook { 
    id?: string;
    provider?: string;
    providerEventId?: string;
    type?: string;
    signatureValid?: boolean;
    status?: AdminDonationWebhookStatusEnum;
    error?: string;
    receivedAt?: string;
    processedAt?: string;
    /**
     * Free-form JSON object
     */
    payload?: object;
}
export enum AdminDonationWebhookStatusEnum {
    Received = 'RECEIVED',
    Processed = 'PROCESSED',
    Ignored = 'IGNORED',
    Failed = 'FAILED'
};



