/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An ad campaign (admin view)
 */
export interface AdminAdCampaign { 
    id?: string;
    advertiserId?: string;
    advertiserName?: string;
    name?: string;
    status?: AdminAdCampaignStatusEnum;
    startAt?: string;
    endAt?: string;
    budgetTotal?: number;
    budgetDaily?: number;
    spent?: number;
    remainingBudget?: number;
    currency?: string;
    pricing?: AdminAdCampaignPricingEnum;
    bidAmount?: number;
    priority?: number;
    frequencyCapPerDay?: number;
    createdAt?: string;
    updatedAt?: string;
}
export enum AdminAdCampaignStatusEnum {
    Draft = 'DRAFT',
    Active = 'ACTIVE',
    Paused = 'PAUSED',
    Ended = 'ENDED'
};
export enum AdminAdCampaignPricingEnum {
    Cpm = 'CPM',
    Cpc = 'CPC',
    Flat = 'FLAT'
};



