/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A credit ledger entry (admin view)
 */
export interface AdminCreditEntry { 
    id?: string;
    userId?: string;
    amount?: number;
    balanceAfter?: number;
    type?: AdminCreditEntryTypeEnum;
    reason?: string;
    referenceType?: string;
    referenceId?: string;
    /**
     * Free-form JSON object
     */
    details?: object;
    note?: string;
    createdBy?: string;
    createdAt?: string;
}
export enum AdminCreditEntryTypeEnum {
    Earn = 'EARN',
    Spend = 'SPEND',
    Grant = 'GRANT',
    Expire = 'EXPIRE',
    Adjust = 'ADJUST',
    Reversal = 'REVERSAL'
};



