/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RatingResponse } from './ratingResponse';


export interface AdminRating { 
    rating: RatingResponse;
    raterId: string;
    rateeId: string;
    interactionId: string;
    moderationState: AdminRatingModerationStateEnum;
    hiddenReason?: string | null;
    hiddenBy?: string | null;
    hiddenAt?: string | null;
}
export enum AdminRatingModerationStateEnum {
    Ok = 'OK',
    Hidden = 'HIDDEN'
};



