/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReferenceResponse } from './referenceResponse';


export interface AdminReference { 
    reference: ReferenceResponse;
    authorId: string;
    subjectId: string;
    moderationState: AdminReferenceModerationStateEnum;
    hiddenReason?: string | null;
}
export enum AdminReferenceModerationStateEnum {
    Ok = 'OK',
    Hidden = 'HIDDEN'
};



