/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeletionRequestSummary } from './deletionRequestSummary';
import { AuditLogEntry } from './auditLogEntry';
import { ConsentSummary } from './consentSummary';
import { AdminUserSummary } from './adminUserSummary';


/**
 * Account detail for the admin console
 */
export interface AdminUserDetail { 
    account: AdminUserSummary;
    suspensionReason?: string | null;
    updatedAt: string;
    deletedAt?: string | null;
    consents: Array<ConsentSummary>;
    /**
     * Public trading-area label; coordinates are never exposed
     */
    locationLabel?: string | null;
    deletionRequest?: DeletionRequestSummary;
    recentAuditEntries: Array<AuditLogEntry>;
}

