/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An advertiser (admin view)
 */
export interface AdminAdvertiser { 
    id?: string;
    name?: string;
    contactEmail?: string;
    status?: AdminAdvertiserStatusEnum;
    createdAt?: string;
    updatedAt?: string;
}
export enum AdminAdvertiserStatusEnum {
    Active = 'ACTIVE',
    Paused = 'PAUSED',
    Archived = 'ARCHIVED'
};



