/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminPaymentParty } from './adminPaymentParty';


/**
 * A dispute in the admin queue
 */
export interface AdminDisputeSummary { 
    id: string;
    tradeId: string;
    paymentId: string;
    status: AdminDisputeSummaryStatusEnum;
    reason: AdminDisputeSummaryReasonEnum;
    openedAt: string;
    resolvedAt?: string | null;
    amount?: number | null;
    currency?: string | null;
    buyer?: AdminPaymentParty;
    seller?: AdminPaymentParty;
}
export enum AdminDisputeSummaryStatusEnum {
    Open = 'OPEN',
    UnderReview = 'UNDER_REVIEW',
    Frozen = 'FROZEN',
    ResolvedBuyer = 'RESOLVED_BUYER',
    ResolvedSeller = 'RESOLVED_SELLER',
    ResolvedSplit = 'RESOLVED_SPLIT',
    Closed = 'CLOSED'
};
export enum AdminDisputeSummaryReasonEnum {
    NotReceived = 'NOT_RECEIVED',
    NotAsDescribed = 'NOT_AS_DESCRIBED',
    Counterfeit = 'COUNTERFEIT',
    Damaged = 'DAMAGED',
    Other = 'OTHER'
};



