/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdTargetingRule } from './adTargetingRule';


export interface AdTargetingRequest { 
    rules: Array<AdTargetingRule>;
}

