/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdTargetingRule { 
    kind: AdTargetingRuleKindEnum;
    /**
     * GAME/TAG slug, REGION code (americas-north), COUNTRY (CA), SUBDIVISION (CA-QC), PLAN code or ANONYMOUS
     */
    value: string;
}
export enum AdTargetingRuleKindEnum {
    Game = 'GAME',
    Region = 'REGION',
    Country = 'COUNTRY',
    Subdivision = 'SUBDIVISION',
    Tag = 'TAG',
    Plan = 'PLAN'
};



