/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdvertiserRequest { 
    name: string;
    /**
     * Business contact (admin only)
     */
    contactEmail?: string;
    /**
     * ACTIVE (default), PAUSED or ARCHIVED
     */
    status?: AdvertiserRequestStatusEnum;
}
export enum AdvertiserRequestStatusEnum {
    Active = 'ACTIVE',
    Paused = 'PAUSED',
    Archived = 'ARCHIVED'
};



