/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnalyticsDailyCount } from './analyticsDailyCount';


export interface AnalyticsSummary { 
    source: string;
    /**
     * Where events are published (log or pubsub)
     */
    transport: string;
    from: string;
    to: string;
    total: number;
    /**
     * Event type to count
     */
    totals: { [key: string]: number; };
    daily: Array<AnalyticsDailyCount>;
}

