/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A collector blocked by the caller
 */
export interface BlockedUser { 
    id: string;
    handle: string;
    displayName: string;
    avatarUrl?: string | null;
    blockedAt: string;
}

