/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CardImageCacheGameStatus { 
    game: string;
    provider: string;
    images: { [key: string]: number; };
    cachedBytes: number;
}

