/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CardImageCacheGameStatus } from './cardImageCacheGameStatus';


/**
 * Local card image cache state
 */
export interface CardImageCacheStatus { 
    usedBytes: number;
    reservedBytes: number;
    remainingBytes: number;
    limitBytes: number;
    usedMb: number;
    reservedMb: number;
    remainingMb: number;
    limitMb: number;
    files: number;
    activeReservations: number;
    images: { [key: string]: number; };
    games: Array<CardImageCacheGameStatus>;
    reconciledAt?: string;
}

