/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CollectorMarker } from './collectorMarker';
import { PublicInventoryItem } from './publicInventoryItem';


/**
 * A collector near you holding the card
 */
export interface CardHolderResult { 
    collector: CollectorMarker;
    item: PublicInventoryItem;
}

