/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Catalog sync request
 */
export interface CatalogSyncRequest { 
    gameSlug: string;
    provider: string;
    mode: CatalogSyncRequestModeEnum;
}
export enum CatalogSyncRequestModeEnum {
    Full = 'FULL',
    Incremental = 'INCREMENTAL'
};



