/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RatingSummaryResponse } from './ratingSummaryResponse';
import { RatingResponse } from './ratingResponse';


export interface CollectorRatingsPage { 
    items: Array<RatingResponse>;
    nextCursor?: string | null;
    hasMore: boolean;
    summary: RatingSummaryResponse;
}

