/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProfileLocation } from './profileLocation';
import { CollectorTag } from './collectorTag';
import { CollectorRating } from './collectorRating';


/**
 * Public collector profile
 */
export interface CollectorProfileResponse { 
    id: string;
    handle: string;
    displayName: string;
    avatarUrl?: string | null;
    bio: string;
    games: Array<string>;
    tags: Array<CollectorTag>;
    /**
     * Null unless the collector is discoverable and set a location
     */
    location?: ProfileLocation;
    memberSince: string;
    lastActiveBucket: CollectorProfileResponseLastActiveBucketEnum;
    onlineStatus: CollectorProfileResponseOnlineStatusEnum;
    rating: CollectorRating;
    publicBinderCount: number;
    /**
     * Whether the caller may start a conversation
     */
    canMessage: boolean;
    isBlocked: boolean;
}
export enum CollectorProfileResponseLastActiveBucketEnum {
    Today = 'TODAY',
    ThisWeek = 'THIS_WEEK',
    ThisMonth = 'THIS_MONTH',
    LongerAgo = 'LONGER_AGO',
    Hidden = 'HIDDEN'
};
export enum CollectorProfileResponseOnlineStatusEnum {
    Online = 'ONLINE',
    Offline = 'OFFLINE',
    Hidden = 'HIDDEN'
};



