/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LastMessage } from './lastMessage';
import { ConversationParticipant } from './conversationParticipant';


/**
 * A private conversation of the caller
 */
export interface ConversationSummary { 
    id: string;
    other: ConversationParticipant;
    lastMessage?: LastMessage;
    unreadCount: number;
    muted: boolean;
    archived: boolean;
    createdAt: string;
}

