/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreatePostRequest { 
    body: string;
    /**
     * Optional shared printing
     */
    cardPrintingId?: string;
    /**
     * Optional shared public binder
     */
    binderId?: string;
}

