/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateDeletionRequest { 
    /**
     * Optional free text; never copied into the audit log
     */
    reason?: string | null;
    /**
     * The owner wants their export first; GET /me/export stays available while the deletion is pending
     */
    exportFirst?: boolean | null;
}

