/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferTradeItemRequest } from './offerTradeItemRequest';


export interface CreateOfferRequest { 
    /**
     * The seller\'s public inventory item
     */
    itemId: string;
    /**
     * CASH, TRADE or MIXED; derived from cashAmount and tradeItemIds when absent
     */
    kind?: CreateOfferRequestKindEnum;
    /**
     * Cash part (CASH, MIXED), 2 decimals
     */
    cashAmount?: number;
    /**
     * ISO 4217; default: the item\'s currency
     */
    currency?: string;
    /**
     * The buyer\'s own cards in trade (TRADE, MIXED), at most 10; public visibility not required
     */
    tradeItemIds?: Array<OfferTradeItemRequest>;
    /**
     * Optional note to the seller
     */
    message?: string;
    /**
     * 1-168, default 72
     */
    expiresInHours?: number;
    /**
     * Ask for payment protection (cash offers; needs the protectedPayments feature, Phase 9 flows)
     */
    protectionRequested?: boolean;
}
export enum CreateOfferRequestKindEnum {
    Cash = 'CASH',
    Trade = 'TRADE',
    Mixed = 'MIXED'
};



