/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * cardId or printingId is required (the card of a printing is derived). rarity, conditionMin, edition and language must belong to the game\'s GameSchema. Matching compares platform regions (no radius, no distance; ADR 0017).
 */
export interface CreateWishlistItemRequest { 
    cardId?: string;
    printingId?: string;
    rarity?: string;
    conditionMin?: string;
    edition?: string;
    language?: string;
    maxPrice?: number;
    currency?: string;
    tradePreference?: CreateWishlistItemRequestTradePreferenceEnum;
    notes?: string;
    active?: boolean;
}
export enum CreateWishlistItemRequestTradePreferenceEnum {
    Any = 'ANY',
    Trade = 'TRADE',
    Sale = 'SALE'
};



