/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A new binder
 */
export interface CreateBinderRequest { 
    name: string;
    description?: string;
    kind?: CreateBinderRequestKindEnum;
    /**
     * PRIVATE, PUBLIC or TEMPORARILY_PUBLIC (until publicUntil, at most 30 days ahead)
     */
    visibility?: CreateBinderRequestVisibilityEnum;
    publicUntil?: string;
    coverPrintingId?: string;
}
export enum CreateBinderRequestKindEnum {
    Collection = 'COLLECTION',
    Trade = 'TRADE',
    Sale = 'SALE',
    Deck = 'DECK',
    Custom = 'CUSTOM'
};
export enum CreateBinderRequestVisibilityEnum {
    Private = 'PRIVATE',
    Public = 'PUBLIC',
    TemporarilyPublic = 'TEMPORARILY_PUBLIC'
};



