/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The entitlement a spend unlocked
 */
export interface CreditUnlock { 
    id?: string;
    featureKey?: string;
    value?: string;
    expiresAt?: string;
}

