/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A credit ledger entry
 */
export interface CreditEntry { 
    id?: string;
    amount?: number;
    balanceAfter?: number;
    type?: CreditEntryTypeEnum;
    reason?: string;
    product?: string;
    expiresAt?: string;
    createdAt?: string;
}
export enum CreditEntryTypeEnum {
    Earn = 'EARN',
    Spend = 'SPEND',
    Grant = 'GRANT',
    Expire = 'EXPIRE',
    Adjust = 'ADJUST',
    Reversal = 'REVERSAL'
};



