/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreditUnlock } from './creditUnlock';
import { CreditEntry } from './creditEntry';


/**
 * Result of a credit spend
 */
export interface CreditSpend { 
    entry?: CreditEntry;
    balance?: number;
    entitlement?: CreditUnlock;
    duplicate?: boolean;
}

