/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferSummary } from './offerSummary';


/**
 * Cursor-paginated list
 */
export interface CursorPageOfferSummary { 
    /**
     * Items of the current slice
     */
    items?: Array<OfferSummary>;
    /**
     * Opaque cursor to pass as the cursor parameter for the next slice; absent when there is no more data
     */
    nextCursor?: string | null;
    /**
     * Whether another slice exists
     */
    hasMore?: boolean;
}

