/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Pending account deletion request
 */
export interface DeletionRequestSummary { 
    id: string;
    status: string;
    requestedAt: string;
    scheduledFor: string;
}

