/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Entry of a dispute\'s timeline
 */
export interface DisputeEvent { 
    id: string;
    /**
     * OPENED, EVIDENCE_ADDED, MESSAGE_POSTED, NOTE_ADDED, UNDER_REVIEW, FROZEN, UNFROZEN, RESOLVED
     */
    event: string;
    /**
     * BUYER, SELLER, ADMIN or null (platform)
     */
    actorRole?: string | null;
    details: { [key: string]: any | null; };
    createdAt: string;
}

