/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A received donation webhook
 */
export interface DonationWebhookReceipt { 
    received: boolean;
    duplicate: boolean;
    webhookEventId?: string | null;
    type: string;
}

