/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Accepted amounts and currencies
 */
export interface DonationSettings { 
    minAmount?: number;
    maxAmount?: number;
    currencies?: Array<string>;
    updatedBy?: string;
    updatedAt?: string;
}

