/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DonationCheckoutRequest { 
    /**
     * Within donations.min_amount..max_amount
     */
    amount: number;
    /**
     * One of donations.currencies
     */
    currency: string;
    /**
     * Optional note to the team (never public)
     */
    message?: string;
    /**
     * List my display name among the supporters (default false)
     */
    publicThanks?: boolean;
}

