/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Per-user override of a plan feature or limit
 */
export interface Entitlement { 
    id?: string;
    userId?: string;
    featureKey?: string;
    /**
     * Features: true/false (null = true). Limits: a number (null = unlimited)
     */
    value?: string;
    source?: EntitlementSourceEnum;
    expiresAt?: string;
    grantedBy?: string;
    note?: string;
    createdAt?: string;
    revokedAt?: string;
}
export enum EntitlementSourceEnum {
    Subscription = 'SUBSCRIPTION',
    AdminGrant = 'ADMIN_GRANT',
    Promo = 'PROMO',
    CreditPurchase = 'CREDIT_PURCHASE'
};



