/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Freshness of a listing
 */
export interface Freshness { 
    /**
     * ACTIVE (recently confirmed), AGING, STALE (still public), HIDDEN (not public until confirmed)
     */
    state: FreshnessStateEnum;
    confirmedAt: string;
    updatedAt: string;
    label: string;
}
export enum FreshnessStateEnum {
    Active = 'ACTIVE',
    Aging = 'AGING',
    Stale = 'STALE',
    Hidden = 'HIDDEN'
};



