/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HistoryFlag { 
    id: string;
    reason: HistoryFlagReasonEnum;
    createdAt: string;
}
export enum HistoryFlagReasonEnum {
    BannedTerm = 'BANNED_TERM',
    RateThreshold = 'RATE_THRESHOLD',
    RepeatedContent = 'REPEATED_CONTENT',
    ReportThreshold = 'REPORT_THRESHOLD'
};



