/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HistoryListingStatus { 
    paused: boolean;
    source?: HistoryListingStatusSourceEnum | null;
    pausedAt?: string | null;
    strikes: number;
}
export enum HistoryListingStatusSourceEnum {
    Unresponsive = 'UNRESPONSIVE',
    ReportThreshold = 'REPORT_THRESHOLD',
    Moderation = 'MODERATION',
    Admin = 'ADMIN'
};



