/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HistoryReport { 
    id: string;
    reason: HistoryReportReasonEnum;
    status: HistoryReportStatusEnum;
    createdAt: string;
    resolutionAction?: HistoryReportResolutionActionEnum | null;
}
export enum HistoryReportReasonEnum {
    Scam = 'SCAM',
    Counterfeit = 'COUNTERFEIT',
    Harassment = 'HARASSMENT',
    Spam = 'SPAM',
    InappropriateBehavior = 'INAPPROPRIATE_BEHAVIOR',
    MisleadingListings = 'MISLEADING_LISTINGS',
    Other = 'OTHER'
};
export enum HistoryReportStatusEnum {
    Open = 'OPEN',
    UnderReview = 'UNDER_REVIEW',
    Actioned = 'ACTIONED',
    Dismissed = 'DISMISSED'
};
export enum HistoryReportResolutionActionEnum {
    None = 'NONE',
    Warning = 'WARNING',
    ListingsPaused = 'LISTINGS_PAUSED',
    Suspended = 'SUSPENDED',
    Banned = 'BANNED'
};



