/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A re-encoded image waiting to be attached
 */
export interface ImageUploadResponse { 
    uploadId: string;
    url: string;
    width: number;
    height: number;
    expiresAt: string;
}

