/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InventoryItemImage } from './inventoryItemImage';
import { InventoryBinderRef } from './inventoryBinderRef';
import { Freshness } from './freshness';
import { InventoryCardRef } from './inventoryCardRef';
import { PrintingSummary } from './printingSummary';


/**
 * An inventory item of the caller
 */
export interface InventoryItemResponse { 
    id: string;
    printing: PrintingSummary;
    card: InventoryCardRef;
    /**
     * Null when unfiled
     */
    binder?: InventoryBinderRef;
    quantity: number;
    condition: string;
    language: string;
    edition: string;
    finish: string;
    askingPrice?: number | null;
    currency: string;
    availability: InventoryItemResponseAvailabilityEnum;
    acceptsOffers: boolean;
    /**
     * Private notes (only ever returned to the owner)
     */
    notes: string;
    publicNotes: string;
    /**
     * PRIVATE, PUBLIC or TEMPORARILY_PUBLIC (until publicUntil, at most 30 days ahead)
     */
    visibility: InventoryItemResponseVisibilityEnum;
    /**
     * End of a TEMPORARILY_PUBLIC publication
     */
    publicUntil?: string | null;
    /**
     * Whether the item is public right now (visibility, expiry, binder, freshness, the owner\'s account and privacy settings)
     */
    effectivePublic: boolean;
    freshness: Freshness;
    images: Array<InventoryItemImage>;
    createdAt: string;
    updatedAt: string;
}
export enum InventoryItemResponseAvailabilityEnum {
    CollectionOnly = 'COLLECTION_ONLY',
    Trade = 'TRADE',
    Sale = 'SALE',
    TradeOrSale = 'TRADE_OR_SALE',
    NotAvailable = 'NOT_AVAILABLE'
};
export enum InventoryItemResponseVisibilityEnum {
    Private = 'PRIVATE',
    Public = 'PUBLIC',
    TemporarilyPublic = 'TEMPORARILY_PUBLIC'
};



