/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Card of an inventory item
 */
export interface InventoryCardRef { 
    id: string;
    name: string;
    game: string;
}

