/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Owner photo of an inventory item
 */
export interface InventoryItemImage { 
    id: string;
    url: string;
    width: number;
    height: number;
    sortOrder: number;
}

