/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A published legal document
 */
export interface LegalDocument { 
    documentType: LegalDocumentDocumentTypeEnum;
    version: string;
    title: string;
    /**
     * Path on the web app
     */
    url: string;
    requiredAtRegistration: boolean;
}
export enum LegalDocumentDocumentTypeEnum {
    Terms = 'TERMS',
    Privacy = 'PRIVACY',
    CommunityGuidelines = 'COMMUNITY_GUIDELINES',
    MarketplacePolicy = 'MARKETPLACE_POLICY',
    PaymentProtection = 'PAYMENT_PROTECTION',
    RefundDispute = 'REFUND_DISPUTE',
    Cookies = 'COOKIES',
    AcceptableUse = 'ACCEPTABLE_USE'
};



