/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Pause of the public listings and strikes
 */
export interface ListingStatus { 
    paused: boolean;
    source?: ListingStatusSourceEnum | null;
    /**
     * Moderator or admin reason (admin views only)
     */
    reason?: string | null;
    pausedAt?: string | null;
    /**
     * End of a timed pause; null while paused = until resumed
     */
    pausedUntil?: string | null;
    /**
     * Whether the owner can resume by confirming (UNRESPONSIVE)
     */
    canResume: boolean;
    strikes: number;
    maxStrikes: number;
    unansweredConversations30d: number;
    evaluatedAt?: string | null;
}
export enum ListingStatusSourceEnum {
    Unresponsive = 'UNRESPONSIVE',
    ReportThreshold = 'REPORT_THRESHOLD',
    Moderation = 'MODERATION',
    Admin = 'ADMIN'
};



