/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Public item matching the request\'s filters
 */
export interface MatchingItem { 
    itemId: string;
    printingId: string;
    printingCode?: string | null;
    cardId: string;
    cardName: string;
    game: string;
    availability: MatchingItemAvailabilityEnum;
    askingPrice?: number | null;
    currency: string;
    condition: string;
    language: string;
    edition: string;
    acceptsOffers: boolean;
    /**
     * ACTIVE (recently confirmed), AGING, STALE (still public), HIDDEN (not public until confirmed)
     */
    freshness: MatchingItemFreshnessEnum;
}
export enum MatchingItemAvailabilityEnum {
    CollectionOnly = 'COLLECTION_ONLY',
    Trade = 'TRADE',
    Sale = 'SALE',
    TradeOrSale = 'TRADE_OR_SALE',
    NotAvailable = 'NOT_AVAILABLE'
};
export enum MatchingItemFreshnessEnum {
    Active = 'ACTIVE',
    Aging = 'AGING',
    Stale = 'STALE',
    Hidden = 'HIDDEN'
};



