/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OnboardingStatus } from './onboardingStatus';
import { RequiredConsent } from './requiredConsent';


/**
 * The calling collector\'s own account
 */
export interface MeResponse { 
    id: string;
    handle: string;
    displayName?: string | null;
    email?: string | null;
    emailVerified: boolean;
    roles: Set<MeResponseRolesEnum>;
    status: MeResponseStatusEnum;
    avatarUrl?: string | null;
    createdAt: string;
    lastActiveAt?: string | null;
    onboarding: OnboardingStatus;
    /**
     * Current legal document versions still to accept; while non-empty every non-exempt route answers 428
     */
    requiredConsents: Array<RequiredConsent>;
    plan: string;
    /**
     * Platform region of the collector\'s declared location (ADR 0017); null without a location. Clients browse it by default
     */
    homeRegion?: string | null;
}
export enum MeResponseRolesEnum {
    User = 'USER',
    PremiumUser = 'PREMIUM_USER',
    Moderator = 'MODERATOR',
    Admin = 'ADMIN',
    SuperAdmin = 'SUPER_ADMIN'
};
export enum MeResponseStatusEnum {
    Active = 'ACTIVE',
    Suspended = 'SUSPENDED',
    DeletionRequested = 'DELETION_REQUESTED',
    Deleted = 'DELETED'
};



