/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Photo of an IMAGE message
 */
export interface MessageImage { 
    url: string;
    width: number;
    height: number;
}

