/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CursorPageCreditEntry } from './cursorPageCreditEntry';
import { CreditProduct } from './creditProduct';


/**
 * The caller\'s credits (non-cash)
 */
export interface MyCredits { 
    balance?: number;
    entries?: CursorPageCreditEntry;
    products?: Array<CreditProduct>;
    withdrawable?: boolean;
    transferable?: boolean;
}

