/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicPoint } from './publicPoint';
import { TradingAreaResponse } from './tradingAreaResponse';


/**
 * The caller\'s own location settings
 */
export interface MyLocationResponse { 
    /**
     * The chosen trading area (owner only)
     */
    tradingArea?: TradingAreaResponse;
    /**
     * The derived point other collectors see; null while not discoverable
     */
    publicPoint?: PublicPoint;
    discoverable: boolean;
}

