/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MyLocation } from './myLocation';


/**
 * The caller\'s own location settings
 */
export interface MyLocationResponse { 
    /**
     * Null while no location is set
     */
    location?: MyLocation;
    discoverable: boolean;
}

