/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Country, state/province and optional city
 */
export interface MyLocation { 
    regionCode: string;
    regionName: string;
    countryCode: string;
    countryName: string;
    subdivisionCode: string;
    subdivisionName: string;
    label: string;
    city?: string | null;
    /**
     * Show the city on the public profile
     */
    showCity: boolean;
}

