/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SearchCentre } from './searchCentre';
import { CollectorMarker } from './collectorMarker';


/**
 * Collectors on the map around a centre
 */
export interface NearbyCollectorsResponse { 
    center: SearchCentre;
    /**
     * Radius used (plan-capped, 0.1 km steps)
     */
    radiusKm: number;
    collectors: Array<CollectorMarker>;
    /**
     * Matching collectors
     */
    total: number;
    /**
     * Whether more collectors match than returned (`limit`)
     */
    truncated: boolean;
}

