/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An in-app notification
 */
export interface NotificationResponse { 
    id: string;
    type: NotificationResponseTypeEnum;
    title: string;
    body: string;
    /**
     * Ids of the objects concerned and `deepLink` (web path, e.g. /wishlist/<id> or /messages/<conversationId>)
     */
    data: { [key: string]: any | null; };
    createdAt: string;
    /**
     * Null while unread
     */
    readAt?: string | null;
}
export enum NotificationResponseTypeEnum {
    WishlistMatch = 'WISHLIST_MATCH',
    Message = 'MESSAGE',
    OfferReceived = 'OFFER_RECEIVED',
    OfferAccepted = 'OFFER_ACCEPTED',
    OfferCountered = 'OFFER_COUNTERED',
    OfferDeclined = 'OFFER_DECLINED',
    OfferCancelled = 'OFFER_CANCELLED',
    OfferExpired = 'OFFER_EXPIRED',
    BinderExpiring = 'BINDER_EXPIRING',
    BinderStaleWarning = 'BINDER_STALE_WARNING',
    BinderHidden = 'BINDER_HIDDEN',
    RatingReceived = 'RATING_RECEIVED',
    TradeUpdate = 'TRADE_UPDATE',
    ShipmentStatus = 'SHIPMENT_STATUS',
    PaymentUpdate = 'PAYMENT_UPDATE',
    ReportDecision = 'REPORT_DECISION',
    System = 'SYSTEM'
};



