/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Offer referenced by a message (Phase 8)
 */
export interface OfferLink { 
    id: string;
    status: string;
    summary: string;
}

