/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CollectorRating } from './collectorRating';
import { Place } from './place';


/**
 * A party of an offer or a trade: handle, display name, avatar, rating and, while discoverable, their state/province and country
 */
export interface OfferParty { 
    id: string;
    handle: string;
    displayName: string;
    avatarUrl?: string | null;
    /**
     * State/province and country; null unless the collector is discoverable with a location
     */
    place?: Place;
    rating: CollectorRating;
}

