/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferTerms } from './offerTerms';


/**
 * Entry of an offer\'s history
 */
export interface OfferEvent { 
    id: string;
    /**
     * The proposal concerned
     */
    offerId: string;
    event: OfferEventEventEnum;
    /**
     * Null for the platform (expiry)
     */
    actorRole?: OfferEventActorRoleEnum | null;
    /**
     * Decline / cancel reason
     */
    reason?: string | null;
    /**
     * The proposal after the event
     */
    terms: OfferTerms;
    createdAt: string;
}
export enum OfferEventEventEnum {
    Created = 'CREATED',
    Countered = 'COUNTERED',
    Accepted = 'ACCEPTED',
    Declined = 'DECLINED',
    Cancelled = 'CANCELLED',
    Expired = 'EXPIRED',
    Viewed = 'VIEWED'
};
export enum OfferEventActorRoleEnum {
    Buyer = 'BUYER',
    Seller = 'SELLER'
};



