/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Which onboarding steps the user completed
 */
export interface OnboardingStatus { 
    profileComplete: boolean;
    tradingAreaSet: boolean;
    interestsSet: boolean;
}

