/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Which onboarding steps the user completed
 */
export interface OnboardingStatus { 
    profileComplete: boolean;
    tradingAreaSet: boolean;
    interestsSet: boolean;
    /**
     * Whether the collector confirmed being 18 years of age or older (AGE_CONFIRMATION consent). Added 2026-10-05; optional so older clients keep working.
     */
    ageConfirmed?: boolean;
}

