/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminBinder } from './adminBinder';


/**
 * Offset-paginated list
 */
export interface PageResponseAdminBinder { 
    /**
     * Items of the current page
     */
    items?: Array<AdminBinder>;
    /**
     * Zero-based page index
     */
    page?: number;
    /**
     * Requested page size
     */
    size?: number;
    /**
     * Total number of items across all pages
     */
    totalItems?: number;
    /**
     * Total number of pages
     */
    totalPages?: number;
}

