/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PauseListingsRequest { 
    /**
     * Why (audited; never shown to the collector)
     */
    reason: string;
    /**
     * Optional end of the pause (future)
     */
    until?: string | null;
}

