/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentsAutoReleaseJobResult { 
    /**
     * payments.auto_release_enabled
     */
    enabled?: boolean;
    /**
     * Buyers reminded
     */
    reminded?: number;
    /**
     * Payouts released
     */
    released?: number;
    /**
     * Releases that failed (retried next run)
     */
    failed?: number;
}

