/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A refund to the buyer
 */
export interface PaymentRefund { 
    id: string;
    amount: number;
    currency: string;
    reason: string;
    /**
     * ADMIN, DISPUTE or SYSTEM
     */
    source: string;
    /**
     * PENDING, SUCCEEDED or FAILED
     */
    status: string;
    requestedBy?: string | null;
    createdAt: string;
    completedAt?: string | null;
}

