/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * State/province and country of a collector; never a city or a coordinate
 */
export interface Place { 
    regionCode: string;
    countryCode: string;
    countryName: string;
    /**
     * ISO 3166-2 code, or the country\'s alpha-2 code for a whole-country pseudo-subdivision
     */
    subdivisionCode: string;
    subdivisionName: string;
    /**
     * State/province + country, or the country alone
     */
    label: string;
}

