/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlanFeature } from './planFeature';
import { PlanLimit } from './planLimit';


/**
 * Subscription plan with its features and limits
 */
export interface Plan { 
    code?: string;
    name?: string;
    description?: string;
    monthlyPrice?: number;
    currency?: string;
    features?: Array<PlanFeature>;
    limits?: Array<PlanLimit>;
}

