/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Usage limit of a plan
 */
export interface PlanLimit { 
    key?: string;
    kind?: PlanLimitKindEnum;
    window?: PlanLimitWindowEnum;
    /**
     * null means unlimited
     */
    limit?: number;
    description?: string;
}
export enum PlanLimitKindEnum {
    Counter = 'COUNTER',
    Cap = 'CAP'
};
export enum PlanLimitWindowEnum {
    Day = 'DAY',
    Month = 'MONTH',
    Total = 'TOTAL'
};



