/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MarketPrice } from './marketPrice';
import { PrintingImage } from './printingImage';


/**
 * Printing of a card
 */
export interface PrintingSummary { 
    id?: string;
    cardId?: string;
    setId?: string;
    setCode?: string;
    setName?: string;
    collectorNumber?: string;
    printingCode?: string;
    rarity?: string;
    edition?: string;
    language?: string;
    finish?: string;
    images?: Array<PrintingImage>;
    marketPrice?: MarketPrice;
}

