/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Privacy settings of the caller
 */
export interface PrivacySettings { 
    /**
     * Appear on the map / in nearby searches (default false)
     */
    discoverable: boolean;
    /**
     * Default true
     */
    showDistance: boolean;
    /**
     * Default false
     */
    showOnlineStatus: boolean;
    /**
     * Default true
     */
    showLastActive: boolean;
    /**
     * Default MEMBERS
     */
    profileVisibility: PrivacySettingsProfileVisibilityEnum;
    /**
     * Default MEMBERS_WITH_PROFILE
     */
    messagingPermission: PrivacySettingsMessagingPermissionEnum;
    /**
     * Default false
     */
    wishlistVisible: boolean;
    /**
     * Default true
     */
    searchDiscoverable: boolean;
}
export enum PrivacySettingsProfileVisibilityEnum {
    Public = 'PUBLIC',
    Members = 'MEMBERS',
    Private = 'PRIVATE'
};
export enum PrivacySettingsMessagingPermissionEnum {
    Everyone = 'EVERYONE',
    MembersWithProfile = 'MEMBERS_WITH_PROFILE',
    Nobody = 'NOBODY'
};



