/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProblemDetailErrorsInner } from './problemDetailErrorsInner';
import { ProblemDetailRequiredConsentsInner } from './problemDetailRequiredConsentsInner';


/**
 * RFC 9457 problem details with OrenjiTrade extensions
 */
export interface ProblemDetail { 
    type: string;
    title: string;
    status: number;
    detail?: string;
    instance?: string;
    errorCode: ProblemDetailErrorCodeEnum;
    message: string;
    requestId: string;
    timestamp: string;
    /**
     * Per-field errors of VALIDATION_FAILED problems
     */
    errors?: Array<ProblemDetailErrorsInner>;
    /**
     * Documents to accept (TERMS_ACCEPTANCE_REQUIRED problems)
     */
    requiredConsents?: Array<ProblemDetailRequiredConsentsInner>;
    /**
     * End of a temporary suspension (ACCOUNT_SUSPENDED)
     */
    suspendedUntil?: string;
    /**
     * Seconds to wait (RATE_LIMITED problems)
     */
    retryAfterSeconds?: number;
    /**
     * Open obligations preventing an account deletion (DELETION_BLOCKED), e.g. OPEN_DISPUTE
     */
    blockers?: Array<string>;
    /**
     * Limit that was reached (LIMIT_REACHED), e.g. binder.views.per_day
     */
    limitKey?: string;
    /**
     * Effective limit of the caller (LIMIT_REACHED)
     */
    limit?: number;
    /**
     * Usage in the current window, or the requested value of a cap (LIMIT_REACHED)
     */
    used?: number;
    /**
     * When the window resets (LIMIT_REACHED; absent for totals and caps)
     */
    resetsAt?: string;
    /**
     * The caller\'s plan (LIMIT_REACHED), e.g. FREE
     */
    planCode?: string;
    /**
     * Where to send the user to upgrade (LIMIT_REACHED): /premium
     */
    upgradeUrl?: string;
    /**
     * Feature flag that is off for the caller (FEATURE_DISABLED)
     */
    feature?: string;
    /**
     * Current status of the resource when a state conflicts (INVALID_STATE_TRANSITION, CONFLICT, ALREADY_SUBSCRIBED)
     */
    currentStatus?: string;
    /**
     * The caller\'s live subscription (ALREADY_SUBSCRIBED)
     */
    subscriptionId?: string;
    /**
     * The caller\'s credit balance (INSUFFICIENT_CREDITS)
     */
    balance?: number;
    /**
     * Credits the action needs (INSUFFICIENT_CREDITS)
     */
    cost?: number;
    /**
     * Why a referral code cannot be redeemed (REFERRAL_NOT_ALLOWED): SELF, ALREADY_REDEEMED, ACCOUNT_TOO_OLD, REFERRER_LIMIT
     */
    reason?: string;
}
export enum ProblemDetailErrorCodeEnum {
    ValidationFailed = 'VALIDATION_FAILED',
    NotFound = 'NOT_FOUND',
    Forbidden = 'FORBIDDEN',
    Unauthenticated = 'UNAUTHENTICATED',
    ReauthenticationRequired = 'REAUTHENTICATION_REQUIRED',
    AccountSuspended = 'ACCOUNT_SUSPENDED',
    FeatureDisabled = 'FEATURE_DISABLED',
    MessagingBlocked = 'MESSAGING_BLOCKED',
    MessageBlocked = 'MESSAGE_BLOCKED',
    PostBlocked = 'POST_BLOCKED',
    DuplicatePost = 'DUPLICATE_POST',
    RatingNotEligible = 'RATING_NOT_ELIGIBLE',
    AlreadyRated = 'ALREADY_RATED',
    RatingEditWindowClosed = 'RATING_EDIT_WINDOW_CLOSED',
    ReportAlreadyOpen = 'REPORT_ALREADY_OPEN',
    CannotReportSelf = 'CANNOT_REPORT_SELF',
    OffersNotAccepted = 'OFFERS_NOT_ACCEPTED',
    OfferAlreadyOpen = 'OFFER_ALREADY_OPEN',
    StaleOffer = 'STALE_OFFER',
    NotYourTurn = 'NOT_YOUR_TURN',
    InvalidStateTransition = 'INVALID_STATE_TRANSITION',
    ItemUnavailable = 'ITEM_UNAVAILABLE',
    TradingBlocked = 'TRADING_BLOCKED',
    SellerNotOnboarded = 'SELLER_NOT_ONBOARDED',
    DisputeWindowClosed = 'DISPUTE_WINDOW_CLOSED',
    EvidenceLimitReached = 'EVIDENCE_LIMIT_REACHED',
    WebhookSignatureInvalid = 'WEBHOOK_SIGNATURE_INVALID',
    AlreadySubscribed = 'ALREADY_SUBSCRIBED',
    InsufficientCredits = 'INSUFFICIENT_CREDITS',
    ReferralNotAllowed = 'REFERRAL_NOT_ALLOWED',
    Conflict = 'CONFLICT',
    HandleTaken = 'HANDLE_TAKEN',
    DeletionBlocked = 'DELETION_BLOCKED',
    TermsAcceptanceRequired = 'TERMS_ACCEPTANCE_REQUIRED',
    RateLimited = 'RATE_LIMITED',
    LimitReached = 'LIMIT_REACHED',
    PayloadTooLarge = 'PAYLOAD_TOO_LARGE',
    UnsupportedMediaType = 'UNSUPPORTED_MEDIA_TYPE',
    InternalError = 'INTERNAL_ERROR',
    NotImplemented = 'NOT_IMPLEMENTED',
    ServiceUnavailable = 'SERVICE_UNAVAILABLE'
};



