/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicBinderOwner } from './publicBinderOwner';
import { Freshness } from './freshness';


/**
 * Public binder of a collector
 */
export interface PublicBinderSummary { 
    id: string;
    name: string;
    description: string;
    kind: PublicBinderSummaryKindEnum;
    /**
     * End of a temporary publication
     */
    publicUntil?: string | null;
    /**
     * Public items
     */
    itemCount: number;
    games: Array<string>;
    coverImageUrl?: string | null;
    freshness: Freshness;
    /**
     * Owner block; present in search results (`GET /search`), absent in a collector\'s own binder list
     */
    owner?: PublicBinderOwner;
}
export enum PublicBinderSummaryKindEnum {
    Collection = 'COLLECTION',
    Trade = 'TRADE',
    Sale = 'SALE',
    Deck = 'DECK',
    Custom = 'CUSTOM'
};



