/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicOwnerLocation } from './publicOwnerLocation';


/**
 * Owner of a public binder
 */
export interface PublicBinderOwner { 
    id: string;
    handle: string;
    displayName: string;
    avatarUrl?: string | null;
    /**
     * Null unless the collector is discoverable
     */
    location?: PublicOwnerLocation;
}

