/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InventoryItemImage } from './inventoryItemImage';
import { InventoryBinderRef } from './inventoryBinderRef';
import { Freshness } from './freshness';
import { InventoryCardRef } from './inventoryCardRef';
import { PrintingSummary } from './printingSummary';


/**
 * A public inventory item
 */
export interface PublicInventoryItem { 
    id: string;
    printing: PrintingSummary;
    card: InventoryCardRef;
    /**
     * Public binder holding the item, if any
     */
    binder?: InventoryBinderRef;
    quantity: number;
    condition: string;
    language: string;
    edition: string;
    finish: string;
    askingPrice?: number | null;
    currency: string;
    availability: PublicInventoryItemAvailabilityEnum;
    acceptsOffers: boolean;
    publicNotes: string;
    images: Array<InventoryItemImage>;
    freshness: Freshness;
}
export enum PublicInventoryItemAvailabilityEnum {
    CollectionOnly = 'COLLECTION_ONLY',
    Trade = 'TRADE',
    Sale = 'SALE',
    TradeOrSale = 'TRADE_OR_SALE',
    NotAvailable = 'NOT_AVAILABLE'
};



