/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Approximate location (never a point)
 */
export interface PublicOwnerLocation { 
    publicLabel: string;
    /**
     * Null unless the request is signed in, the caller has a trading area and the owner shows distances
     */
    distanceBucket?: PublicOwnerLocationDistanceBucketEnum | null;
}
export enum PublicOwnerLocationDistanceBucketEnum {
    Lt1Km = 'LT_1KM',
    Km15 = 'KM_1_5',
    Km510 = 'KM_5_10',
    Km1025 = 'KM_10_25',
    Km2550 = 'KM_25_50',
    Gt50Km = 'GT_50KM'
};



