/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RatingSummaryResponse { 
    average?: number | null;
    count: number;
    communication?: number | null;
    conditionAccuracy?: number | null;
    shipping?: number | null;
    meetupReliability?: number | null;
}

