/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RatingBreakdown } from './ratingBreakdown';
import { RatingAuthor } from './ratingAuthor';


/**
 * A rating of a collector
 */
export interface RatingResponse { 
    id: string;
    rater: RatingAuthor;
    overall: number;
    breakdown: RatingBreakdown;
    comment?: string | null;
    createdAt: string;
    updatedAt: string;
    interactionKind: RatingResponseInteractionKindEnum;
    /**
     * End of the author\'s 14-day edit window
     */
    editableUntil: string;
}
export enum RatingResponseInteractionKindEnum {
    Trade = 'TRADE',
    OfferAccepted = 'OFFER_ACCEPTED',
    ConversationQualified = 'CONVERSATION_QUALIFIED'
};



