/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RatingAuthor } from './ratingAuthor';


/**
 * A public reference about a collector
 */
export interface ReferenceResponse { 
    id: string;
    author: RatingAuthor;
    body: string;
    createdAt: string;
}

