/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegionSubdivision } from './regionSubdivision';


export interface RegionCountry { 
    code: string;
    name: string;
    regionCode: string;
    /**
     * Inactive countries are listed to admins only
     */
    active: boolean;
    subdivisions: Array<RegionSubdivision>;
}

