/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommunityAuthor } from './communityAuthor';


/**
 * A reply to a community post
 */
export interface ReplyResponse { 
    id: string;
    postId: string;
    author: CommunityAuthor;
    body: string;
    createdAt: string;
    canDelete: boolean;
    moderationState: ReplyResponseModerationStateEnum;
}
export enum ReplyResponseModerationStateEnum {
    Ok = 'OK',
    Flagged = 'FLAGGED',
    Removed = 'REMOVED'
};



