/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportContextRequest { 
    source: ReportContextRequestSourceEnum;
    conversationId?: string;
    postId?: string;
    binderId?: string;
}
export enum ReportContextRequestSourceEnum {
    Profile = 'PROFILE',
    Conversation = 'CONVERSATION',
    Post = 'POST',
    Binder = 'BINDER'
};



