/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportedConversationMessage } from './reportedConversationMessage';


export interface ReportedConversation { 
    id: string;
    /**
     * Newest first (at most 50)
     */
    messages: Array<ReportedConversationMessage>;
}

