/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportMember } from './reportMember';


export interface ReportSummary { 
    id: string;
    status: ReportSummaryStatusEnum;
    reason: ReportSummaryReasonEnum;
    contextSource: ReportSummaryContextSourceEnum;
    reporter: ReportMember;
    reportedUser: ReportMember;
    assignee?: ReportMember;
    createdAt: string;
    resolvedAt?: string | null;
    resolutionAction?: ReportSummaryResolutionActionEnum | null;
    /**
     * Open reports against the reported collector
     */
    openReportsAgainstUser: number;
}
export enum ReportSummaryStatusEnum {
    Open = 'OPEN',
    UnderReview = 'UNDER_REVIEW',
    Actioned = 'ACTIONED',
    Dismissed = 'DISMISSED'
};
export enum ReportSummaryReasonEnum {
    Scam = 'SCAM',
    Counterfeit = 'COUNTERFEIT',
    Harassment = 'HARASSMENT',
    Spam = 'SPAM',
    InappropriateBehavior = 'INAPPROPRIATE_BEHAVIOR',
    MisleadingListings = 'MISLEADING_LISTINGS',
    Other = 'OTHER'
};
export enum ReportSummaryContextSourceEnum {
    Profile = 'PROFILE',
    Conversation = 'CONVERSATION',
    Post = 'POST',
    Binder = 'BINDER'
};
export enum ReportSummaryResolutionActionEnum {
    None = 'NONE',
    Warning = 'WARNING',
    ListingsPaused = 'LISTINGS_PAUSED',
    Suspended = 'SUSPENDED',
    Banned = 'BANNED'
};



