/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportedUserSummary { 
    id: string;
    handle: string;
    displayName: string;
    avatarUrl?: string | null;
    status: ReportedUserSummaryStatusEnum;
    suspendedUntil?: string | null;
    bannedAt?: string | null;
    memberSince: string;
}
export enum ReportedUserSummaryStatusEnum {
    Active = 'ACTIVE',
    Suspended = 'SUSPENDED',
    DeletionRequested = 'DELETION_REQUESTED',
    Deleted = 'DELETED'
};



