/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportReasonOption { 
    code: ReportReasonOptionCodeEnum;
    label: string;
    description: string;
}
export enum ReportReasonOptionCodeEnum {
    Scam = 'SCAM',
    Counterfeit = 'COUNTERFEIT',
    Harassment = 'HARASSMENT',
    Spam = 'SPAM',
    InappropriateBehavior = 'INAPPROPRIATE_BEHAVIOR',
    MisleadingListings = 'MISLEADING_LISTINGS',
    Other = 'OTHER'
};



