/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A legal document version that must be accepted
 */
export interface RequiredConsent { 
    documentType: RequiredConsentDocumentTypeEnum;
    version: string;
}
export enum RequiredConsentDocumentTypeEnum {
    Terms = 'TERMS',
    Privacy = 'PRIVACY',
    CommunityGuidelines = 'COMMUNITY_GUIDELINES',
    MarketplacePolicy = 'MARKETPLACE_POLICY',
    PaymentProtection = 'PAYMENT_PROTECTION',
    RefundDispute = 'REFUND_DISPUTE',
    Cookies = 'COOKIES',
    AcceptableUse = 'ACCEPTABLE_USE',
    AgeConfirmation = 'AGE_CONFIRMATION'
};



