/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResolveDisputeRequest { 
    outcome: ResolveDisputeRequestOutcomeEnum;
    /**
     * SPLIT: refunded to the buyer (more than 0, less than the refundable amount); BUYER: empty or the whole refundable amount; SELLER: empty or 0
     */
    refundAmount?: number;
    /**
     * Shown to both parties with the decision
     */
    note: string;
}
export enum ResolveDisputeRequestOutcomeEnum {
    Buyer = 'BUYER',
    Seller = 'SELLER',
    Split = 'SPLIT'
};



