/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Mixed autocomplete entry
 */
export interface SearchSuggestion { 
    type: SearchSuggestionTypeEnum;
    /**
     * Id of the card, printing, set, collector, binder or tag
     */
    id: string;
    label: string;
    sublabel?: string | null;
    imageUrl?: string | null;
    game?: string | null;
    /**
     * Navigation key: the handle of a COLLECTOR, the slug of a TAG
     */
    slug?: string | null;
    /**
     * Card of a PRINTING entry
     */
    cardId?: string | null;
}
export enum SearchSuggestionTypeEnum {
    Card = 'CARD',
    Printing = 'PRINTING',
    Set = 'SET',
    Collector = 'COLLECTOR',
    Binder = 'BINDER',
    Tag = 'TAG'
};



