/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Card set
 */
export interface SetSummary { 
    id?: string;
    game?: string;
    code?: string;
    name?: string;
    releaseDate?: string;
    totalCards?: number;
    series?: string;
    printingCount?: number;
}

