/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Shipping confirmation of a protected trade
 */
export interface ShipmentSummary { 
    carrier?: string | null;
    trackingNumber?: string | null;
    /**
     * The seller\'s notes for the buyer
     */
    sellerNotes?: string | null;
    shippedAt: string;
    /**
     * When receipt was confirmed
     */
    deliveredAt?: string | null;
}

