/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobStatus } from './jobStatus';
import { OutboxBacklog } from './outboxBacklog';


export interface SystemHealth { 
    checkedAt: string;
    status: string;
    /**
     * Component to status
     */
    components: { [key: string]: string; };
    outbox: OutboxBacklog;
    notificationsPendingDispatch: number;
    jobs: Array<JobStatus>;
}

