/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Profile tag
 */
export interface TagResponse { 
    id: string;
    slug: string;
    label: string;
    category: TagResponseCategoryEnum;
    /**
     * Number of profiles carrying the tag
     */
    usageCount: number;
}
export enum TagResponseCategoryEnum {
    Game = 'GAME',
    Role = 'ROLE',
    Style = 'STYLE',
    Logistics = 'LOGISTICS',
    Language = 'LANGUAGE',
    Custom = 'CUSTOM'
};



