/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferParty } from './offerParty';
import { PaymentSummary } from './paymentSummary';
import { TradeEvent } from './tradeEvent';
import { TradeNextAction } from './tradeNextAction';
import { OfferResponse } from './offerResponse';
import { DisputeSummary } from './disputeSummary';


/**
 * A trade as one of its two parties sees it
 */
export interface TradeResponse { 
    id: string;
    /**
     * The accepted offer (item, parties, terms, history)
     */
    offer: OfferResponse;
    viewerRole: TradeResponseViewerRoleEnum;
    counterparty: OfferParty;
    kind: TradeResponseKindEnum;
    cashAmount?: number | null;
    currency?: string | null;
    status: TradeResponseStatusEnum;
    protectionEnabled: boolean;
    /**
     * Both parties marked an in-person meetup
     */
    meetup: boolean;
    buyerMarkedMeetup: boolean;
    sellerMarkedMeetup: boolean;
    buyerConfirmedAt?: string | null;
    sellerConfirmedAt?: string | null;
    nextAction: TradeNextAction;
    /**
     * What the caller may call now
     */
    allowedOperations: Array<TradeResponseAllowedOperationsEnum>;
    /**
     * Oldest first
     */
    timeline: Array<TradeEvent>;
    /**
     * Payment protection (Phase 9); null for now
     */
    payment?: PaymentSummary;
    /**
     * Dispute (Phase 9); null for now
     */
    dispute?: DisputeSummary;
    cancelReason?: string | null;
    createdAt: string;
    updatedAt: string;
    completedAt?: string | null;
    cancelledAt?: string | null;
}
export enum TradeResponseViewerRoleEnum {
    Buyer = 'BUYER',
    Seller = 'SELLER'
};
export enum TradeResponseKindEnum {
    Cash = 'CASH',
    Trade = 'TRADE',
    Mixed = 'MIXED'
};
export enum TradeResponseStatusEnum {
    Agreed = 'AGREED',
    AwaitingPayment = 'AWAITING_PAYMENT',
    Paid = 'PAID',
    Shipped = 'SHIPPED',
    Received = 'RECEIVED',
    Completed = 'COMPLETED',
    Cancelled = 'CANCELLED',
    Disputed = 'DISPUTED'
};
export enum TradeResponseAllowedOperationsEnum {
    MarkMeetup = 'MARK_MEETUP',
    ConfirmCompletion = 'CONFIRM_COMPLETION',
    Cancel = 'CANCEL'
};



