/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Trading area chosen by the owner
 */
export interface TradingAreaResponse { 
    lat: number;
    lng: number;
    radiusKm: number;
    source: TradingAreaResponseSourceEnum;
    label?: string | null;
}
export enum TradingAreaResponseSourceEnum {
    Manual = 'MANUAL',
    Device = 'DEVICE'
};



