/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Entry of a trade\'s timeline
 */
export interface TradeEvent { 
    id: string;
    /**
     * CREATED, MEETUP_PROPOSED, MEETUP_AGREED, PROTECTION_REMOVED, COMPLETION_CONFIRMED, COMPLETED, CANCELLED; Phase 9: PAYMENT_STARTED, PAYMENT_FAILED, PAYMENT_CANCELLED, PAYMENT_SECURED, SHIPPED, RECEIPT_CONFIRMED, PAYOUT_RELEASED, DISPUTE_OPENED, DISPUTE_RESOLVED, REFUNDED
     */
    event: string;
    /**
     * Null for the platform
     */
    actorRole?: TradeEventActorRoleEnum | null;
    /**
     * Event data (statuses, roles, transfers of a completion, the cancel reason)
     */
    details: { [key: string]: any | null; };
    createdAt: string;
}
export enum TradeEventActorRoleEnum {
    Buyer = 'BUYER',
    Seller = 'SELLER'
};



