/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SetSummary } from './setSummary';
import { PrintingSummary } from './printingSummary';
import { SearchResolution } from './searchResolution';
import { CardSummary } from './cardSummary';
import { CollectorMarker } from './collectorMarker';
import { PublicBinderSummary } from './publicBinderSummary';


/**
 * Unified search results
 */
export interface UnifiedSearchResponse { 
    query: string;
    cards: Array<CardSummary>;
    printings: Array<PrintingSummary>;
    sets: Array<SetSummary>;
    /**
     * Platform region the collectors and binders were searched in
     */
    region: string;
    /**
     * Holders of the resolved printing/card in the region (with matchingItems), otherwise collectors of the region matching the text
     */
    collectors: Array<CollectorMarker>;
    /**
     * Public binders, each with its owner block
     */
    binders: Array<PublicBinderSummary>;
    resolved: SearchResolution;
}

