/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlanFeatureChange } from './planFeatureChange';


/**
 * Plan change
 */
export interface UpdatePlanRequest { 
    name: string;
    description?: string;
    monthlyPrice: number;
    currency: string;
    active: boolean;
    sortOrder: number;
    features?: Array<PlanFeatureChange>;
}

