/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateCommunityChannelRequest { 
    name?: string;
    description?: string;
    status?: UpdateCommunityChannelRequestStatusEnum;
    postRateLimitPerHour?: number;
    sortOrder?: number;
    /**
     * Game slug; blank removes it
     */
    game?: string;
    /**
     * City; blank removes it
     */
    regionLabel?: string;
}
export enum UpdateCommunityChannelRequestStatusEnum {
    Active = 'ACTIVE',
    Archived = 'ARCHIVED'
};



