/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Usage limit change (takes effect at once on every instance)
 */
export interface UpdateUsageLimitRequest { 
    unlimited: boolean;
    maxValue?: number;
    window?: UpdateUsageLimitRequestWindowEnum;
    description?: string;
}
export enum UpdateUsageLimitRequestWindowEnum {
    Day = 'DAY',
    Month = 'MONTH',
    Total = 'TOTAL'
};



