/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateLocationRequest { 
    /**
     * ISO 3166-1 alpha-2 code of an active country of GET /regions
     */
    countryCode: string;
    /**
     * A subdivision code of that country (GET /regions)
     */
    subdivisionCode: string;
    /**
     * Optional city, at most 80 characters after trimming; never geocoded. Null or blank clears it
     */
    city?: string | null;
    /**
     * Show the city on the public profile (default true)
     */
    showCity?: boolean | null;
}

