/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateRolesRequest { 
    /**
     * Complete role set; USER is always kept
     */
    roles: Set<UpdateRolesRequestRolesEnum>;
}
export enum UpdateRolesRequestRolesEnum {
    User = 'USER',
    PremiumUser = 'PREMIUM_USER',
    Moderator = 'MODERATOR',
    Admin = 'ADMIN',
    SuperAdmin = 'SUPER_ADMIN'
};



