/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateProfileTagsRequest { 
    /**
     * Ids of existing active tags
     */
    tagIds?: Array<string>;
    /**
     * Free labels (2-24 characters, banned-term check); created as CUSTOM tags or matched to an existing tag with the same slug
     */
    customLabels?: Array<string>;
}

