/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * New freshness thresholds (days)
 */
export interface UpdateDelistPolicyRequest { 
    name?: string;
    agingAfterDays: number;
    staleAfterDays: number;
    hiddenAfterDays: number;
    warnBeforeHiddenDays: number;
    maxStrikes?: number;
    unansweredAfterHours?: number;
}

