/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateTradingAreaRequest { 
    /**
     * Centre latitude (stored rounded to 3 decimals)
     */
    lat: number;
    /**
     * Centre longitude (stored rounded to 3 decimals)
     */
    lng: number;
    radiusKm: number;
    /**
     * MANUAL (default) or DEVICE; DEVICE only records where the centre came from, the server still snaps it
     */
    source?: UpdateTradingAreaRequestSourceEnum | null;
}
export enum UpdateTradingAreaRequestSourceEnum {
    Manual = 'MANUAL',
    Device = 'DEVICE'
};



