/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateProfileRequest { 
    /**
     * 3-24 characters [a-z0-9_] (input is trimmed and lower-cased); unique case-insensitively; reserved words refused (409 HANDLE_TAKEN)
     */
    handle: string;
    displayName: string;
    bio?: string | null;
    games?: Array<string>;
    languages?: Array<string>;
}

