/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Usage limit of a plan
 */
export interface UsageLimit { 
    id?: string;
    key?: string;
    kind?: UsageLimitKindEnum;
    window?: UsageLimitWindowEnum;
    /**
     * The limit; null means unlimited
     */
    maxValue?: number;
    description?: string;
    updatedBy?: string;
    updatedAt?: string;
}
export enum UsageLimitKindEnum {
    Counter = 'COUNTER',
    Cap = 'CAP'
};
export enum UsageLimitWindowEnum {
    Day = 'DAY',
    Month = 'MONTH',
    Total = 'TOTAL'
};



