/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Items per visibility
 */
export interface VisibilityCounts { 
    PRIVATE: number;
    PUBLIC: number;
    TEMPORARILY_PUBLIC: number;
}

