/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WishlistCardRef } from './wishlistCardRef';
import { PrintingSummary } from './printingSummary';
import { WishPriceTerm } from './wishPriceTerm';


/**
 * A card the caller is looking for
 */
export interface WishlistItemResponse { 
    id: string;
    game: string;
    /**
     * Null only if the catalog lost the card
     */
    card?: WishlistCardRef;
    /**
     * The wished printing; null = any printing
     */
    printing?: PrintingSummary;
    /**
     * Any printing of this rarity; null = any rarity
     */
    rarity?: string | null;
    /**
     * Public note (\"\" = none)
     */
    note: string;
    nearMintOnly: boolean;
    priceTerm?: WishPriceTerm;
    createdAt: string;
    updatedAt: string;
}

