/**
 * OrenjiTrade API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WishPriceTerm } from './wishPriceTerm';


/**
 * The price terms a wish may choose
 */
export interface WishPriceTermsResponse { 
    /**
     * In display order
     */
    terms: Array<WishPriceTerm>;
}

