import fs from 'node:fs';
import path from 'node:path';

import { fireEvent, screen } from '@testing-library/react-native';

import LegalDocumentScreen from '@/app/legal/[key]';
import LegalIndexScreen from '@/app/legal/index';
import { LEGAL_DOCUMENT_LIST } from '@/src/legal/legalContent';

import { LEGAL_DOCUMENTS } from '../support/fixtures';
import { mockApi, ok, problem } from '../support/mockApi';
import { mockParams, mockRouter, resetRouterMock } from '../support/router';
import { renderWithProviders, resetAppState } from '../test-utils';

jest.mock('expo-router', () => require('../support/router').expoRouterMock());

beforeEach(() => {
  resetRouterMock();
  resetAppState();
});

describe('Legal pages', () => {
  it('lists every document with the version the API publishes', async () => {
    mockApi({ 'GET /api/v1/public/legal/documents': ok(LEGAL_DOCUMENTS) });
    renderWithProviders(<LegalIndexScreen />);
    expect(screen.getByTestId('legal-draft-banner')).toBeOnTheScreen();
    for (const document of LEGAL_DOCUMENT_LIST) {
      expect(screen.getByRole('link', { name: document.title })).toBeOnTheScreen();
    }
    // Terms, privacy and cookies are published in the fixture.
    expect(await screen.findAllByText(/Current version 2026-09-01\./)).toHaveLength(3);
    fireEvent.press(screen.getByRole('link', { name: 'Terms of Service' }));
    expect(mockRouter.push).toHaveBeenCalledWith({
      pathname: '/legal/[key]',
      params: { key: 'terms' },
    });
  });

  it('renders a document in-app with the version to accept, even when the API is down', async () => {
    mockParams.current = { key: 'terms' };
    mockApi({ 'GET /api/v1/public/legal/documents': ok(LEGAL_DOCUMENTS) });
    const { unmount } = renderWithProviders(<LegalDocumentScreen />);
    expect(screen.getByRole('header', { name: 'Terms of Service' })).toBeOnTheScreen();
    expect(await screen.findByTestId('legal-published-version')).toHaveTextContent(
      /Version to accept: 2026-09-01/
    );
    unmount();

    mockApi({ 'GET /api/v1/public/legal/documents': problem(503, 'SERVICE_UNAVAILABLE', 'down') });
    renderWithProviders(<LegalDocumentScreen />);
    expect(screen.getByRole('header', { name: 'Terms of Service' })).toBeOnTheScreen();
    expect(screen.queryByTestId('legal-published-version')).toBeNull();
  });

  it('handles an unknown document', () => {
    mockParams.current = { key: 'nope' };
    mockApi({});
    renderWithProviders(<LegalDocumentScreen />);
    expect(screen.getByText('Unknown legal document')).toBeOnTheScreen();
    fireEvent.press(screen.getByRole('button', { name: 'Open legal index' }));
    expect(mockRouter.replace).toHaveBeenCalledWith('/legal');
  });

  it('ships exactly the texts of the web app (npm run sync:legal)', () => {
    const root = path.resolve(__dirname, '..', '..');
    const web = fs
      .readFileSync(
        path.join(root, '..', 'web-angular', 'src', 'app', 'features', 'legal', 'legal-content.ts'),
        'utf8'
      )
      .replace(/\r\n/g, '\n');
    const mobile = fs
      .readFileSync(path.join(root, 'src', 'legal', 'legalContent.ts'), 'utf8')
      .replace(/\r\n/g, '\n');
    expect(mobile.endsWith(web)).toBe(true);
    expect(mobile.startsWith('// GENERATED by `npm run sync:legal`')).toBe(true);
  });
});
